### ISSUE TITLE
multiBamSummary BED-file : ValueError: invalid literal for int() with base 10: 'NA'

### ISSUE THREAD

**Issue by hemantgujar** [deeptools/deepTools#1014]
Hi 

Can anyone help with the following error. Thanking you. 

`deeptools --version`
deeptools 3.5.0

`multiBamSummary BED-file --BED ../test.bed --bamfiles $ddir/bam_files/*.bam --outFileName $wdir/bm_results.npz --outRawCounts $wdir/readCounts.tab --smartLabels --numberOfProcessors max/2 --verbose --minMappingQuality 20`

step size is 10000
Traceback (most recent call last):
  File "/software/deepTools/bin/multiBamSummary", line 14, in <module>
    main(args)
  File "/software/python_package/deeptools/multiBamSummary.py", line 250, in main
    num_reads_per_bin = c.run(allArgs=args)
  File "/software/python_package/deeptools/countReadsPerBin.py", line 368, in run
    transcript_id_designator=transcript_id_designator)
  File "/software/python_package/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/software/python_package/deeptoolsintervals/parse.py", line 595, in __init__
    self.parseBED(fp, line, 3, labelColumn)
  File "/software/python_package/deeptoolsintervals/parse.py", line 362, in parseBED
    self.parseBEDcore(line, ncols)
  File "/software/python_package/deeptoolsintervals/parse.py", line 225, in parseBEDcore
    if int(cols[1]) < 0:
ValueError: invalid literal for int() with base 10: 'NA'

**Comment by dpryan79** [comment]
You have an NA where there should be a number in the coordinates.

**Comment by hemantgujar** [comment]
i dont understand where

**Comment by LeilyR** [comment]
check your bed file, it is a 3 column file where columns should be tab separated. Look for na in the 3rd column

**Comment by hemantgujar** [comment]
nice. ok that solved the problem. thanks.
