### ISSUE TITLE
I met problems in computeMatrix 

### ISSUE THREAD

**Issue by wuheng9** [deeptools/deepTools#1022]
Hi,
I met problems when I run the computeMatrix program. The errors are as following:

File "miniconda/computeMatrix", line 14, in <module>
    main(args)
  File "/miniconda/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "miniconda/lib/python3.7/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "miniconda/lib/python3.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "miniconda/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 597, in __init__
    self.parseBED(fp, line, 6, labelColumn)
  File "miniconda/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 333, in parseBED
    sys.stderr.write("Warning, the '{0}' group had no valid entries! Removing it.\n".format(self.labels[self.labelIdx]))
IndexError: list index out of range

Is this problem from the .bed file? 

I am looking forward to your reply.

Best,

Wu

**Comment by dpryan79** [comment]
Yes, this indicates a formatting issue with your BED file.

**Comment by wuheng9** [comment]
Hi Ryan,


Thank you! I will check the BED file.


















At 2020-11-29 20:17:53, "Devon Ryan" <notifications@github.com> wrote:

Yes, this indicates a formatting issue with your BED file.

**Comment by zhangmiaoHZAU** [comment]
I want to plot a profile between TSS-TES region. So I need to create a BED file where the second column represents TSS (Transcription Start Site) and the last column represents TES (Transcription End Site).
And I have a problem about bed file format.

I create the bed file from genome.gff3, the code like this:
`awk '$3 == "gene"' genome.gff3 | awk 'BEGIN{FS="\t|=|;";OFS="\t"}{print $1,$4,$5}' > gene.bed`
The bed file like this:
Chr1    3631    5899
Chr1    5928    8737
Chr1    11649   13714
Chr1    23146   31227
Chr1    31170   33153
Chr1    33379   37871
Chr1    38752   40944
Chr1    44677   44787
Chr1    45296   47019

I can get a normal profile plot using the bed file by deeptools.

But, my question is when generating the BED file, should we not consider the strand (positive or negative) of the genes?

If I consider the positive & negative strand, I use following code to create bed file:
`awk -F'\t' '$3 == "gene" {if($7 == "+") print $1, $4, $5; else print $1, $5, $4}' genome.gff3 > gene.bed`
The bed file like this:
Chr1 3631 5899
Chr1 8737 5928
Chr1 13714 11649
Chr1 23146 31227
Chr1 33153 31170
Chr1 37871 33379
Chr1 40944 38752
Chr1 44677 44787
Chr1 47019 45296

When I try to plot using computematrix , errors like this:

Traceback (most recent call last):
  File "/home/anaconda3/envs/deeptools/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/anaconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/home/anaconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "/home/anaconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/home/anaconda3/envs/deeptools/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 591, in __init__
    ftype = self.inferType(fp, line, labelColumn)
  File "/home/anaconda3/envs/deeptools/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 166, in inferType
    raise RuntimeError('{0} does not seem to be a recognized file type!'.format(self.filename))
RuntimeError: /home/genes.bed does not seem to be a recognized file type!

**Comment by WardDeb** [comment]
That bed file is invalid. start/end should be 5' -> 3'. In case you want deepTools to take strand into account, you can submit BED6, BED12 or GTF format.
