### ISSUE TITLE
legend_location='auto' argument of Profile not accepted by matplotlib

### ISSUE THREAD

**Issue by blaiseli** [deeptools/deepTools#1041]
```
$ deeptools --version
deeptools 3.5.0
$ python --version
Python 3.8.2
$ python -c 'import matplotlib; print(matplotlib.__version__)'
3.3.3
```

The version of matplotlib I use does not allow 'auto' for legend location.

When I run my python script based on deeptools (available here: https://gitlab.pasteur.fr/bli/plotting_scripts/-/blob/master/scripts/create_metagene_profile.py), I get the following error:

```
Traceback (most recent call last):
  File "/home/bli/src/bioinfo_utils/.venv/bin/create_metagene_profile.py", line 396, in <module>
    sys.exit(main())
  File "/home/bli/src/bioinfo_utils/.venv/bin/create_metagene_profile.py", line 384, in main
    compute_matrix(
  File "/home/bli/src/bioinfo_utils/.venv/bin/create_metagene_profile.py", line 285, in compute_matrix
    prof.plot_profile()
  File "/home/bli/src/bioinfo_utils/.venv/lib/python3.8/site-packages/deeptools/plotProfile.py", line 779, in plot_profile
    ax.legend(loc=self.legend_location.replace('-', ' '),
  File "/home/bli/src/bioinfo_utils/.venv/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 417, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/home/bli/src/bioinfo_utils/.venv/lib/python3.8/site-packages/matplotlib/legend.py", line 455, in __init__
    raise ValueError(
ValueError: Unrecognized location 'auto'. Valid locations are
        best
        upper right
        upper left
        lower left
        lower right
        right
        center left
        center right
        lower center
        upper center
        center
```

`prof` is a `deeptools.plotProfile.Profile`.

I suspect something has changes either in deeptools or in matplotlib, because this script used to work.

I would suggest replacing `'auto'` by `'best'` for `legend_location` in the `__init__` of `Profile` in  `deeptools/plotProfile.py`

**Comment by LeilyR** [comment]
You are giht, I think this issue happens if one uses the deeptools api. Can you rebase your PR to develop please?

**Comment by blaiseli** [comment]
I tried to do it. Hoefully I didn't make any mistake.

**Comment by dpryan79** [comment]
Ugh, I hate matplotlib :(

**Comment by LeilyR** [comment]
Already set to `best` in develop. Feel free to use the develop branch and let us know if there is still any wrong with it.
