### ISSUE TITLE
bamCoverage doesn't find any reads in a file that looks fine in IGV

### ISSUE THREAD

**Issue by mchikina** [deeptools/deepTools#1066]
deeptools 3.5.1

I am getting the warning " does not have any mapped reads. Please check that the file is properly indexed and that it contains mapped reads." from a BAM file that looks fine in IGV.
bamCoverage gives an error and no output
Traceback (most recent call last):
  File "/home/mchikina/anaconda3/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/home/mchikina/anaconda3/lib/python3.7/site-packages/deeptools/bamCoverage.py", line 258, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File "/home/mchikina/anaconda3/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 131, in run
    genome_chunk_length = getGenomeChunkLength(bam_handles, self.binLength, self.mappedList)
  File "/home/mchikina/anaconda3/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 337, in getGenomeChunkLength
    genomeChunkLength = int(min(5e6, int(2e6 / (max_reads_per_bp * len(bamHandles)))))
ZeroDivisionError: float division by zero

**Comment by mchikina** [comment]
The issue is with the index generated by bamtools 2.4.1. Regenerating the index with samtools 1.7 fixed the problem.

**Comment by dpryan79** [comment]
Glad that was an easy fix. Bamtools hasn't had a maintenance release in 4 years, so you're better off staying clear of it.
