### ISSUE TITLE
computeMatrix-- socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ryanmboileau** [deeptools/deepTools#1067]
Hello deeptools! 

I am running into an error while attempting to computeMatrix. I am using deeptools 3.5.1 and Python 3.7.6. Although my input bigwigs are processed similarly there seems to be issues with certain samples i.e. it runs fine if I remove these samples.

Ideas? I would like to generate heatmaps for all of my samples and more.
Thanks!

Input

> computeMatrix reference-point \
	--referencePoint center \
	--regionsFileName ${REGIONS} \
	--scoreFileName CT1_Naive_R1_H3K27ac.espike.gt130.ignXMY.e.bw CT1_Form_R1_H3K27ac.espike.gt130.ignXMY.e.bw CT1_Naive_DKO_H3K27ac.espike.gt130.ignXMY.e.bw \
	CT1_Form_DKO_H3K27ac.espike.gt130.ignXMY.e.bw Naive.mRp.clN.bigWig Form.mRp.clN.bigWig Naive_H3K4m3.mRp.clN.bigWig Formative_H3K4m3.mRp.clN.bigWig \
	Naive_H3K27ac_R1.bigWig Naive_H3K27ac_R2.bigWig Form_H3K27ac_R1.bigWig Form_H3K27ac_R2.bigWig Naive_H3K27ac.mRp.clN.bigWig Form_H3K27ac.mRp.clN.bigWig \
	--outFileName ${OUTDIR}/${analysisname}.${uniqueid}.gz \
	--outFileSortedRegions ${OUTDIR}/${analysisname}.sortedregions.${uniqueid}.bed \
	-b 2500 \
	-a 2500 \
	--missingDataAsZero \
	-p 1 \
	--binSize 20 \
	--sortRegions descend \
	--sortUsing mean \
<

Resulting output:
>Preloading the following deepBlue files: Form_H3K27ac.mRp.clN.bigWig
Traceback (most recent call last):
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 412, in main
    res = list(map(db.preloadWrapper, deepBlueFiles))
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/site-packages/deeptools/deepBlue.py", line 114, in preloadWrapper
    res = deepBlue(foo[0], url=args.deepBlueURL, userKey=args.userKey)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/site-packages/deeptools/deepBlue.py", line 138, in __init__
    experimentID = self.getEID()
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/site-packages/deeptools/deepBlue.py", line 164, in getEID
    (status, resps) = self.server.search(self.sample, "experiments", self.userKey)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/c4/home/rboileau/miniconda3/envs/epigenomics/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
<

**Comment by dpryan79** [comment]
Given the error, it seems there's a typo in one of the file names. It's trying to retrieve at least one file from deepBlue rather than the local file system.

**Comment by ryanmboileau** [comment]
Thank you-- hidden special characters were the cause of the issue.

**Comment by dpryan79** [comment]
Ah, those will get you every time.
