### ISSUE TITLE
error in --plotType	overlapped_lines

### ISSUE THREAD

**Issue by wzylin** [deeptools/deepTools#1068]
Hi,
I got error when I set the argument for plotProfile as --plotType overlapped_lines, while setting other arguments like lines or heatmap is fine.
```
plotProfile -m matrix.tab.gz \
 --perGroup \
 --kmeans 4 \
 --samplesLabel "peaks" \
 -z c1 c2 c3 c4\
 -out matrix.png\
 --plotType=overlapped_lines
```

May I ask how can I fix it? Thanks

here is the error messages I got:
````
*Warning* For clustering nan values have to be replaced by zeros
/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py:212: MatplotlibDeprecationWarning:

You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("coolwarm"))

Traceback (most recent call last):
  File "/home/wzylin/miniconda2/envs/deeptools/bin/plotProfile", line 12, in <module>
    main(args)
  File "/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py", line 969, in main
    prof.plot_hexbin()
  File "/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py", line 312, in plot_hexbin
    xticks, xtickslabel = self.getTicks(plot)
  File "/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py", line 198, in getTicks
    xticks, xtickslabel = getProfileTicks(self.hm, self.reference_point_label[idx], self.start_label[idx], self.end_label[idx], idx)
IndexError: list index out of range
```

**Comment by dpryan79** [comment]
What version of matplotlib is installed in that conda environment? This appears to be a new change in it.

**Comment by wzylin** [comment]
> version of matplotlib

I just updated the matpltlib from 3.3 to 3.4
`matplotlib-base                      3.3.3-py37h0c9df89_0 --> 3.4.2-py37hdd32ed1_0`

However, I still got the same error message

```
 plotProfile -m matrix.tab.gz  --perGroup  --kmeans 4  --samplesLabel "peaks"  -z c1 c2 c3 c4 -out profile.png --plotType=overlapped_lines
*Warning* For clustering nan values have to be replaced by zeros
/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py:212: MatplotlibDeprecationWarning:

You are modifying the state of a globally registered colormap. This has been deprecated since 3.3 and in 3.6, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = mpl.cm.get_cmap("coolwarm").copy()

Traceback (most recent call last):
  File "/home/wzylin/miniconda2/envs/deeptools/bin/plotProfile", line 12, in <module>
    main(args)
  File "/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py", line 969, in main
    prof.plot_hexbin()
  File "/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py", line 312, in plot_hexbin
    xticks, xtickslabel = self.getTicks(plot)
  File "/home/wzylin/miniconda2/envs/deeptools/lib/python3.7/site-packages/deeptools/plotProfile.py", line 198, in getTicks
    xticks, xtickslabel = getProfileTicks(self.hm, self.reference_point_label[idx], self.start_label[idx], self.end_label[idx], idx)
IndexError: list index out of range
```

**Comment by LeilyR** [comment]
it would work if you do not use perGroup and overlapped_lines together.

**Comment by wzylin** [comment]
> it would work if you do not use perGroup and overlapped_lines together.

It works now. Thanks!
