### ISSUE TITLE
There are accidents when correctGCBias meets bams with unusual tag

### ISSUE THREAD

**Issue by lssb** [deeptools/deepTools#1072]
When bam's tags content an array, there will be a problem look like:
```
Traceback (most recent call last):
  File "~/miniconda3/envs/dps/bin/correctGCBias", line 12, in <module>
    main(args)
  File "~/miniconda3/envs/dps/lib/python3.7/site-packages/deeptools/correctGCBias.py", line 635, in main
    res = list(map(writeCorrectedSam_wrapper, mp_args))
  File "~/miniconda3/envs/dps/lib/python3.7/site-packages/deeptools/correctGCBias.py", line 288, in writeCorrectedSam_wrapper
    return writeCorrectedSam_worker(*args)
  File "~/miniconda3/envs/dps/lib/python3.7/site-packages/deeptools/correctGCBias.py", line 418, in writeCorrectedSam_worker
    read.set_tags(readTag)
  File "pysam/libcalignedsegment.pyx", line 2571, in pysam.libcalignedsegment.AlignedSegment.set_tags
  File "pysam/libcalignedsegment.pyx", line 396, in pysam.libcalignedsegment.pack_tags
AttributeError: module 'array' has no attribute 'typecode'
````

Ion torrent platform product these bamfiles.
And filter the `ZP` and `ZM` tag could solved this.

**Comment by dpryan79** [comment]
Do you actually need to run correctGCBias with this data? That generally hasn't been needed in a number of years.

**Comment by lssb** [comment]
Thanks for your attention. May someone really need.
