### ISSUE TITLE
ZeroDivisionError when running bamCoverage on bam file, converted from bed

### ISSUE THREAD

**Issue by jpcartailler** [deeptools/deepTools#1074]
Greetings,

I'm getting an error trying to run `bamCoverage` on a bam file (converted from bed via `bedToBam` and then sorted/indexed by `samtools`). Tech details below. Any guidance is much appreciated! 

Regards,
JP

----

- Similar issue to (closed) https://github.com/deeptools/deepTools/issues/550
- deeptools 3.3.1
- Python 3.7.2
- command: `bamCoverage --numberOfProcessors 4 --smoothLength 1 --binSize 1 --normalizeUsing BPM --outFileFormat bigwig --bam BsrDI_rep1_trimmed.bam -o GLOE-Pipe.normalized.bw`
- deeptools output:
```
Warning: the smooth length given (1) is smaller than the bin size (1).

 No smoothing will be done
normalization: BPM
Traceback (most recent call last):
  File "/accre/arch/easybuild/software/MPI/GCC/8.2.0/OpenMPI/3.1.4/deepTools/3.3.1-Python-3.7.2/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/accre/arch/easybuild/software/MPI/GCC/8.2.0/OpenMPI/3.1.4/deepTools/3.3.1-Python-3.7.2/lib/python3.7/site-packages/deeptools/bamCoverage.py", line 258, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File "/accre/arch/easybuild/software/MPI/GCC/8.2.0/OpenMPI/3.1.4/deepTools/3.3.1-Python-3.7.2/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 131, in run
    genome_chunk_length = getGenomeChunkLength(bam_handles, self.binLength, self.mappedList)
  File "/accre/arch/easybuild/software/MPI/GCC/8.2.0/OpenMPI/3.1.4/deepTools/3.3.1-Python-3.7.2/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 334, in getGenomeChunkLength
    max_reads_per_bp = max([float(x) / genomeLength for x in mappedList])
  File "/accre/arch/easybuild/software/MPI/GCC/8.2.0/OpenMPI/3.1.4/deepTools/3.3.1-Python-3.7.2/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 334, in <listcomp>
    max_reads_per_bp = max([float(x) / genomeLength for x in mappedList])
ZeroDivisionError: float division by zero

```

Here is a sample of the input (`samtools view bed/BsrDI_rep1_trimmed.bam | head`):
```
NB501946:79:HNYH2AFXX:2:21305:15980:1356        0       chrIV   118     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:11607:21534:1128        0       chrIV   127     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:21401:15151:508 0       chrIV   149     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:2:21309:25840:918 16      chrIV   334     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:2:21207:22011:467 0       chrIV   503     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:11412:17539:1283        0       chrIV   521     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:2:11210:4278:1970 16      chrIV   553     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:1:11101:11611:381 16      chrIV   853     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:1:21308:10123:1181        16      chrIV   853     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:3:11604:12430:960 16      chrIV   853     255     1M      *       0       0       *       *
```

**Comment by dpryan79** [comment]
Can you remove the `--smoothLength` option?

**Comment by c5creative** [comment]
Thanks for the quick response 👍

1. I removed the `--smoothLength` option as suggested and the warning goes away, however the error (same Traceback) still occurs. In Issue #550, @fidelram stated that "deepTools relies on the genome size reported on the bam file to estimate the number of mapped reads for normalization.  I am afraid that some of this information is lost when converting BED to BAM."

2. My original post's bam input file preview didn't include the header (forgot to include the `-h` argument), but it is indeed there - `samtools view -h BsrDI_rep1_trimmed.bam` (head/tail):

```
@PG     ID:BEDTools_bedToBam    VN:Vv2.28.0
@SQ     SN:chrIV        AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:1531933
@SQ     SN:chrXV        AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:1091291
@SQ     SN:chrVII       AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:1090940
@SQ     SN:chrXII       AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:1078177
@SQ     SN:chrXVI       AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:948066
@SQ     SN:chrXIII      AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:924431
@SQ     SN:chrII        AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:813184
@SQ     SN:chrXIV       AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:784333
@SQ     SN:chrX AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:745751
@SQ     SN:chrXI        AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:666816
@SQ     SN:chrV AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:576874
@SQ     SN:chrVIII      AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:562643
@SQ     SN:chrIX        AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:439888
@SQ     SN:chrIII       AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:316620
@SQ     SN:chrVI        AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:270161
@SQ     SN:chrI AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:230218
@SQ     SN:chrM AS:/data/reference/yeast/sacCer3.chrom.sizes     LN:85779
NB501946:79:HNYH2AFXX:2:21305:15980:1356        0       chrIV   118     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:11607:21534:1128        0       chrIV   127     255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:21401:15151:508 0       chrIV   149  255        1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:2:21309:25840:918 16      chrIV   334  255        1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:2:21207:22011:467 0       chrIV   503  255        1M      *       0       0       *       *
... rows ...
NB501946:79:HNYH2AFXX:3:21507:11578:1341        0       chrIV   1522941 255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:11602:15512:1388        0       chrIV   1522941 255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:3:21610:25232:1757        0       chrIV   1523218 255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:4:11501:8519:866  0       chrIV   1523220 255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:3:11605:21016:1658        0       chrIV   1525162 255     1M      *       0       0       *       *
NB501946:79:HNYH2AFXX:2:21201:1480:1229 0       chrIV   1525267 255     1M      *       0       0       *       *
```

If useful, the bam file is available at https://vanderbilt.box.com/s/bdcsbrief9jjqro9a6b3jnt0h1v7b3sh. Thanks!

**Comment by c5creative** [comment]
The  ` AS:` string in the header was the problem. After figuring out that the chrom lengths were all zeros (via `writeBedGraph.getGenomeChunkLength`), I removed the ` AS:` string (and `\t`) from the headers and bamCoverage is running now.

For anyone with the same issue (with BAM files with headers with the `AS:` string), here is my workaround:
```sh
# Convert to SAM
samtools view -h file.bam > file.temp.sam
# Perform in-place replacement of AS: string - customize to what is your header. Consider better approach for large files.
sed -i -e 's/\tAS:\/data\/p_magnuson_lab\/reference\/yeast\/sacCer3.chrom.sizes\//g' file.temp.sam
# Convert back to BAM
samtools view -S -b file.temp.sam > file.fixed.bam
# Cleanup
rm file.temp.sam
# Index (if your workflow requires it)
samtools index file.fixed.bam
```

**Comment by dpryan79** [comment]
Nice investigative work. I'll have a look at the BAM file, since this sounds like a weird bug in pysam.

**Comment by dpryan79** [comment]
This appears to come down to a possible pysam issue:

```
>>> import pysam
>>> bam = pysam.AlignmentFile("BsrDI_rep1_trimmed.bam")
>>> bam.lengths
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```
 I'm not sure if the extra `AS` tags really causing the error in it or if this is somehow coming down to an obscure htslib bug.
