### ISSUE TITLE
Installation Error using conda

### ISSUE THREAD

**Issue by gene-drive** [deeptools/deepTools#1092]
I am trying to install using `conda install -c bioconda deeptools` and receiving the following error:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 371, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 808, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 288, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/user_vm/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "/home/user_vm/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/home/user_vm/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
        raise self._exception
      File "/home/user_vm/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 145, in query
        self.load()
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 209, in load
        _internal_state = self._load()
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 389, in _load
        _internal_state = self._read_local_repdata(mod_etag_headers.get('_etag'),
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 438, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/user_vm/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 476, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/user_vm/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/home/user_vm/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/user_vm/anaconda3/lib/python3.8/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 294952 column 24 (char 9306112)

`$ /home/user_vm/anaconda3/bin/conda install -c bioconda deeptools`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/user_vm/anaconda3/bin/conda
             CONDA_PREFIX=/home/user_vm/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/user_vm/anaconda3/bin/python
               CONDA_ROOT=/home/user_vm/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/user_vm/anaconda3/bin:/home/user_vm/anaconda3/bin:/home/user_
                          vm/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
                          n:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base
    active env location : /home/user_vm/anaconda3
            shell level : 1
       user config file : /home/user_vm/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/user_vm/anaconda3  (writable)
      conda av data dir : /home/user_vm/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user_vm/anaconda3/pkgs
                          /home/user_vm/.conda/pkgs
       envs directories : /home/user_vm/anaconda3/envs
                          /home/user_vm/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Linux/5.4.0-74-generic linuxmint/20.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

I also later tried using `pip install deeptools` but that failed as well.

**Comment by LeilyR** [comment]
could you please give it a try on a fresh env (not your base env) and see if that solves the issue

**Comment by dpryan79** [comment]
Your connection had an error, I imagine this is transient. Note that the installation command in `conda install -c conda-forge -c bioconda deeptools`
