### ISSUE TITLE
AttributeError: 'module' object has no attribute 'to_hex'（deeptools v2.3.2）

### ISSUE THREAD

**Issue by Golden-proteogenomics** [deeptools/deepTools#1131]
Dear all,
Thank your team to code so great software that I cannot wait to learn when I first know it. However, there is a problem that I cannot resolve in a long time even though I always search Google and repair bugger. could you please help me with that and why?
**(deeptools==2.3.2; matplotlib==1.4.3)**
   I use this `computeMatrix reference-point -p 22 -b 3000 -a 3000 -S ./deeptools/Middle.bw -R ge2.bed -o Middle_TSS.gz` to get Middle result, and I command this `plotHeatmap -m Middle_TSS.gz -o heatma.pdf` so the bugger as follow:

Traceback (most recent call last):
  File "/public/home/jssun_gdl/software/deptols/bin/plotHeatmap", line 7, in <module>
    main()
  File "/public/home/jssun_gdl/software/lib64/python2.7/site-packages/deeptools/plotHeatmap.py", line 895, in main
    interpolation_method=args.interpolationMethod)
  File "/public/home/jssun_gdl/software/lib64/python2.7/site-packages/deeptools/plotHeatmap.py", line 582, in plotMatrix
    ax_list = addProfilePlot(hm, plt, fig, grids, iterNum, iterNum2, perGroup, averageType, plot_type, yAxisLabel, color_list, yMin, yMax, None, None, colorbar_position, label_rotation)
  File "/public/home/jssun_gdl/software/lib64/python2.7/site-packages/deeptools/plotHeatmap.py", line 159, in addProfilePlot
    plot_type=plot_type)
  File "/public/home/jssun_gdl/software/lib64/python2.7/site-packages/deeptools/heatmapper_utilities.py", line 70, in plot_single
    color = pltcolors.to_hex(color, keep_alpha=True)
AttributeError: 'module' object has no attribute 'to_hex'

**Comment by dpryan79** [comment]
That version of deepTools is from 6 years ago and the matplotlib version you're using is similarly old. I'd suggest updating both to more recent versions.
