### ISSUE TITLE
bamCoverage ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by brianpenghe** [deeptools/deepTools#1135]
I was running `bamCoverage` with this command:
`bamCoverage -b unique.nochrM.bam -of bedgraph -bs 1000  --region 'chrX:21519548-21560880' -o  unique.nochrM.bam.1000.bg4`

but got this error:

```
bamFilesList: ['unique.nochrM.bam']
binLength: 1000
numberOfSamples: None
blackListFileName: None
skipZeroOverZero: False
bed_and_bin: False
genomeChunkSize: None
defaultFragmentLength: read length
numberOfProcessors: 1
verbose: False
region: chrX:21519548-21560880:1000
bedFile: None
minMappingQuality: None
ignoreDuplicates: False
chrsToSkip: []
stepSize: 1000
center_read: False
samFlag_include: None
samFlag_exclude: None
minFragmentLength: 0
maxFragmentLength: 0
zerosToNans: False
smoothLength: None
save_data: False
out_file_for_raw_data: None
maxPairedFragmentLength: 1000
Traceback (most recent call last):
  File "/usr/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/usr/lib/python3/dist-packages/deeptools/bamCoverage.py", line 256, in main
    wr.run(writeBedGraph.scaleCoverage, func_args, args.outFileName,
  File "/usr/lib/python3/dist-packages/deeptools/writeBedGraph.py", line 145, in run
    res = mapReduce.mapReduce([func_to_call, func_args],
  File "/usr/lib/python3/dist-packages/deeptools/mapReduce.py", line 76, in mapReduce
    chromSize, region_start, region_end, genomeChunkLength = getUserRegion(chromSize, region)
  File "/usr/lib/python3/dist-packages/deeptools/mapReduce.py", line 206, in getUserRegion
    region_start = int(region[1])
ValueError: invalid literal for int() with base 10: '21519548-21560880'
```
I'm using Deeptools Version 3

**Comment by LeilyR** [comment]
Try chrX:21519548:21560880

**Comment by brianpenghe** [comment]
Yes you are right. THanks!
