### ISSUE TITLE
Install error: `metadata-generation-failed`

### ISSUE THREAD

**Issue by danli349** [deeptools/deepTools#1164]
Hello

Can anyone please tell me what is the reason for this install error?
```
PS C:\Users\lidan> python -m pip install deeptools
Collecting deeptools
  Using cached deepTools-3.5.1-py3-none-any.whl (233 kB)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\lidan\appdata\roaming\python\python38\site-packages (from deeptools) (3.3.3)
Collecting deeptoolsintervals>=0.1.8
  Using cached deeptoolsintervals-0.1.9.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lidan\AppData\Local\Temp\pip-install-3n9d8f8i\deeptoolsintervals_4163aca6099749dda42849e7a158a9ac\setup.py", line 12, in <module>
          for e in sysconfig.get_config_vars('BLDLIBRARY')[0].split():
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
Thanks a a lot

**Comment by danli349** [comment]
@dpryan79 
I see. Thanks.
