### ISSUE TITLE
`computeMatrix` ValueError: invalid literal for int() with base 10: 'random'

### ISSUE THREAD

**Issue by danli349** [deeptools/deepTools#1165]
Hello

```
computeMatrix reference-point --referencePoint center -b 2000 -a 2000 \
-R readcounts/ETV4AAA_vs_EYFP_up.bed \
readcounts/ETV4AAA_vs_EYFP_down.bed \
-S bigwigRPGCmerged/EYFP_merged.bw \
bigwigRPGCmerged/ETV4WT_merged.bw \
bigwigRPGCmerged/ETV4AAA_merged.bw \
bigwigRPGCmerged/TEP_merged.bw \
-p 12 \
-o plotHeatmap/matrix.gz \
--outFileNameMatrix plotHeatmap/matrix.tab

```
I get this error:
```
Traceback (most recent call last):
  File "/home/lid/miniconda3/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 595, in __init__
    self.parseBED(fp, line, 3, labelColumn)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 362, in parseBED
    self.parseBEDcore(line, ncols)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 225, in parseBEDcore
    if int(cols[1]) < 0:
ValueError: invalid literal for int() with base 10: 'random'
```
Can anyone tell me what is the reason for this error?

Thanks a lot

**Comment by dpryan79** [comment]
It looks like your BED file is malformatted. In particular, it appears that the word "random" is in the second column on at least one line.

**Comment by danli349** [comment]
I see. Thanks
