### ISSUE TITLE
module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [deeptools/deepTools#1181]
When running computematrix: 

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/seq2science_PR-944/miniconda/envs/s2s/lib/python3.8/site-packages/seq2science/.snakemake/37f425be7a38235ae34f7926399c06aa_/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/var/lib/jenkins/workspace/seq2science_PR-944/miniconda/envs/s2s/lib/python3.8/site-packages/seq2science/.snakemake/37f425be7a38235ae34f7926399c06aa_/lib/python3.10/site-packages/deeptools/computeMatrix.py", line 438, in main
    hm.save_matrix(args.outFileName)
  File "/var/lib/jenkins/workspace/seq2science_PR-944/miniconda/envs/s2s/lib/python3.8/site-packages/seq2science/.snakemake/37f425be7a38235ae34f7926399c06aa_/lib/python3.10/site-packages/deeptools/heatmapper.py", line 855, in save_matrix
    np.float(score_list[idx])
  File "/var/lib/jenkins/workspace/seq2science_PR-944/miniconda/envs/s2s/lib/python3.8/site-packages/seq2science/.snakemake/37f425be7a38235ae34f7926399c06aa_/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```

**Comment by Maarten-vd-Sande** [comment]
Related to the latest numpy release where these have been deprecated: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

**Comment by Maarten-vd-Sande** [comment]
I updated the bioconda recipe to reflect this change: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/deeptools/meta.yaml#L21

**Comment by y9c** [comment]
https://github.com/deeptools/deepTools/pull/1184
