### ISSUE TITLE
plotHeatmap issue

### ISSUE THREAD

**Issue by BalajiVenkadakrishnan** [deeptools/deepTools#1197]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.5.0
Python 3.9.14

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
plotHeatmap \
>        -m compute_matrix/matrix_pm154_k27me3.gz \
>        -o heatmaps/heatmap_matrix_bival_pm154_k4me3_k27me3_2.png \
>        --plotTitle 'pm154_h3k27me3' --verbose --colorMap bwr

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
Traceback (most recent call last):
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/bin/plotHeatmap", line 12, in <module>
    main(args)
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/deeptools/plotHeatmap.py", line 874, in main
    plotMatrix(hm,
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/deeptools/plotHeatmap.py", line 770, in plotMatrix
    plt.savefig(outFileName, bbox_inches='tight', pdd_inches=0, dpi=dpi, format=image_format)
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/matplotlib/pyplot.py", line 954, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/matplotlib/figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/n/app/deeptools/3.5.0-gcc-9.2.0/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 385, in wrapper
    arguments = signature.bind(*inner_args, **inner_kwargs).arguments
  File "/n/app/python/3.9.14/lib/python3.9/inspect.py", line 3045, in bind
    return self._bind(args, kwargs)
  File "/n/app/python/3.9.14/lib/python3.9/inspect.py", line 3034, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'pdd_inches'

**Comment by JSegueni** [comment]
Hi,
Updating to deeptools 3.5.1 will probably solve that issue.
Have you tried that?

**Comment by Jou-cee** [comment]
plotheatmap -m ESC.gz --out ESC.pdf
 error:Unexpected keyword argument 'pdd_inches'
