### ISSUE TITLE
problem with multithreading deeptools 3.5.2

### ISSUE THREAD

**Issue by asoufiGitHub** [deeptools/deepTools#1229]
I upgraded deeptools to version 3.5.2 and I have been having this error with multithreading using miniconda in linux centos 7.

python --version
Python 3.9.16

deeptools --version
deeptools 3.5.2

computeMatrix reference-point --referencePoint center -R test_file.bed -S test_file2.bw -b 5000 -a 5000 --binSize 10 --sortRegions keep --averageTypeBins sum --missingDataAsZero -o output_matrix.gz -p max/2

Preloading the following deepBlue files: /home/user/work/test_file2.bw
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/user/miniconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/miniconda3/lib/python3.9/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/home/user/miniconda3/lib/python3.9/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 4 required positional arguments: 'url', 'errcode', 'errmsg', and 'headers'

**Comment by asoufiGitHub** [comment]
the problem has been solved. it was an issue with an old installation of matplotlib.
