### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by jeffwhite81** [deeptools/deepTools#1275]
Using deeptools-3.5.4.post1 installed with pip.

computeMatrix is now failing with the following error:

Traceback (most recent call last):
  File "/opt/homebrew/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/opt/homebrew/lib/python3.10/site-packages/deeptools/computeMatrix.py", line 438, in main
    hm.save_matrix(args.outFileName)
  File "/opt/homebrew/lib/python3.10/site-packages/deeptools/heatmapper.py", line 855, in save_matrix
    np.float(score_list[idx])
  File "/opt/homebrew/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by jeffwhite81** [comment]
Issue solved by re-installing Xcode from the App Store.
