### ISSUE TITLE
plotHeatmap set multiple yMax values error

### ISSUE THREAD

**Issue by wddyzxxx** [deeptools/deepTools#1278]
deeptools 3.5.4.post1
Python 3.10.13

plotHeatmap -m ../05_visualization/matrix/H3K4me3_1sc_rep1_4_methods.mtx.gz --refPointLabel "center" -o ../05_visualization/plot/Heatmap_HCT116_H3K4me3_1sc_rep1_4_methods_center.png --dpi 300 --colorList "white,#2600f6" --zMax 300 10 10 300 5 --yMax 300 10 10 300 10
Traceback (most recent call last):
  File "/data/yuanzhen/conda/miniconda/envs/cutag/bin/plotHeatmap", line 8, in <module>
    sys.exit(main())
  File "/data/yuanzhen/conda/miniconda/envs/cutag/lib/python3.10/site-packages/deeptools/plotHeatmap.py", line 876, in main
    plotMatrix(hm,
  File "/data/yuanzhen/conda/miniconda/envs/cutag/lib/python3.10/site-packages/deeptools/plotHeatmap.py", line 587, in plotMatrix
    import matplotlib.tight_layout as tl
ModuleNotFoundError: No module named 'matplotlib.tight_layout'

**Comment by WardDeb** [comment]
Thanks for reporting this, a fix for this sits in #1282, though needs some extra tests. You can stick to an older version, or try to test if the fix works for you by checking out the `plotheatmap_ymax_mpl` branch and installing from there.

Kind regards,

WardDeb
