### ISSUE TITLE
ValueError: could not broadcast input array from shape (11000,) into shape (4400,)

### ISSUE THREAD

**Issue by danli349** [deeptools/deepTools#1300]
Hello:
When I run `computeMatrix`
```bash
computeMatrix reference-point --referencePoint TSS -b -3000 -a 5000 \
--missingDataAsZero \
-bl mm10-blacklist.v2.bed \
-R bed/*.bed \
-S All_bw/*.bw \
-p 12 \
-o plotHeatmap/Active_TSS.gz \
--outFileNameMatrix plotHeatmap/Active_TSS.tab


plotHeatmap  -m plotHeatmap/Active_TSS.gz \
-out plotHeatmap/Active_TSS.pdf \
--outFileSortedRegions plotHeatmap/Active_TSS.bed \
--missingDataColor white \
--dpi 500 \
--colorMap Reds
```
I got the error: 

```bash
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/lid/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/lid/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptools/heatmapper.py", line 174, in compute_sub_matrix_wrapper
    return heatmapper.compute_sub_matrix_worker(*args)
  File "/home/lid/miniconda3/lib/python3.7/site-packages/deeptools/heatmapper.py", line 585, in compute_sub_matrix_worker
    sub_matrix[j, :] = coverage
ValueError: could not broadcast input array from shape (11000,) into shape (4400,)
"""
```

How should I solve this problem?
Thanks a lot

**Comment by danli349** [comment]
Sorry I found the reason, I should use `-b 3000`. Thanks

**Comment by WardDeb** [comment]
Thanks for the report, a force to set these positive has been put in #1301.
