### ISSUE TITLE
"502 Proxy Error" when using bigwigCompare

### ISSUE THREAD

**Issue by Reb08** [deeptools/deepTools#1308]
Good morning, 

I am working with ChIP-seq data. I have two replicates per sample. I am creating a coverage file for each replicate using bamCoverage, merging the two resulting .bw files using bigWigMerge, sorting the file and then obtaining the final merged .bw file using bedGraphToBigWig. I would now like to subtract the input from the merged sample using bigwigCompare. I have been using the following code:

`bigwigCompare -b1  {merged.bw sample file}  -b2  {input.bw file} --operation subtract  -o {output.bw file} --numberOfProcessors max`

However, I keep getting the following error:

"Traceback (most recent call last):
  File "/services/tools/deeptools/3.5.2/bin/bigwigCompare", line 12, in <module>
    main(args)
  File "/services/tools/deeptools/3.5.2/lib/python3.10/site-packages/deeptools/bigwigCompare.py", line 144, in main
    foo = db.deepBlue(deepBlueFiles[0][0], url=args.deepBlueURL, userKey=args.userKey)
  File "/services/tools/deeptools/3.5.2/lib/python3.10/site-packages/deeptools/deepBlue.py", line 138, in __init__
    experimentID = self.getEID()
  File "/services/tools/deeptools/3.5.2/lib/python3.10/site-packages/deeptools/deepBlue.py", line 164, in getEID
    (status, resps) = self.server.search(self.sample, "experiments", self.userKey)
  File "/services/tools/deeptools/3.5.2/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/services/tools/deeptools/3.5.2/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/services/tools/deeptools/3.5.2/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/services/tools/deeptools/3.5.2/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for deepblue.mpi-inf.mpg.de/xmlrpc: 502 Proxy Error>"

(deeptools --version: deeptools 3.5.2;
python --version: Python 3.10.11)

Any idea what could be causing this and how to fix it?

Thank you

**Comment by WardDeb** [comment]
This implies your input files (b1, b2 or both) are not specified correctly. The deepblue support is dropped from 3.5.5 onwards (and thus the error would be more meaningful there).
