### ISSUE TITLE
Unexpected keyword argument 'pdd_inches'

### ISSUE THREAD

**Issue by yeeelwy** [deeptools/deepTools#1314]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.4.3
python 3.8.2

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
plotHeatmap -m xx4_24.mat.gz \
-out xx4_24.png \
--sortUsing sum

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/py_packages/3.8/bin/plotHeatmap", line 12, in <module>
    main(args)
  File "/hpc/packages/minerva-centos7/py_packages/3.8/lib/python3.8/site-packages/deeptools/plotHeatmap.py", line 847, in main
    plotMatrix(hm,
  File "/hpc/packages/minerva-centos7/py_packages/3.8/lib/python3.8/site-packages/deeptools/plotHeatmap.py", line 743, in plotMatrix
    plt.savefig(outFileName, bbox_inches='tight', pdd_inches=0, dpi=dpi, format=image_format)
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages/matplotlib/pyplot.py", line 954, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages/matplotlib/figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 385, in wrapper
    arguments = signature.bind(*inner_args, **inner_kwargs).arguments
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/inspect.py", line 3025, in bind
    return self._bind(args, kwargs)
  File "/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/inspect.py", line 3014, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'pdd_inches'

**Comment by WardDeb** [comment]
No longer an issue with 4.0.0 onwards. Feel free to re-open if this pops up again !
