### ISSUE TITLE
computeMatrix results in AttributeError: module 'numpy' has no attribute 'NAN'

### ISSUE THREAD

**Issue by yonniejon** [deeptools/deepTools#1324]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.5.5
computeMatrix 3.5.5
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux

>>> import numpy as np
>>> np.__version__
'2.1.0'

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
computeMatrix reference-point -S origins_hg19.Q1_or_Q2.bw -R check.bed -o check.bin_size_10000.11000000_before_after.matrix --referencePoint center --binSize 10000 --beforeRegionStartLength 1000000 --afterRegionStartLength 1000000 --missingDataAsZero -p 16

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/cs/cbio/jon/jon_v/lib/python3.11/site-packages/deeptools/heatmapper.py", line 174, in compute_sub_matrix_wrapper
    return heatmapper.compute_sub_matrix_worker(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cs/cbio/jon/jon_v/lib/python3.11/site-packages/deeptools/heatmapper.py", line 379, in compute_sub_matrix_worker
    sub_matrix[:] = np.NAN
                    ^^^^^^
  File "/cs/cbio/jon/jon_v/lib/python3.11/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'NAN'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cs/usr/jrosensk/.local/bin/computeMatrix", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/cs/cbio/jon/jon_v/lib/python3.11/site-packages/deeptools/computeMatrix.py", line 398, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/cs/cbio/jon/jon_v/lib/python3.11/site-packages/deeptools/heatmapper.py", line 252, in computeMatrix
    res, labels = mapReduce.mapReduce([score_file_list, parameters],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cs/cbio/jon/jon_v/lib/python3.11/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'NAN'

**Comment by yonniejon** [comment]
This is a duplicate of https://github.com/deeptools/deepTools/issues/1322
