### ISSUE TITLE
ImportError: cannot import name 'colormaps'

### ISSUE THREAD

**Issue by VihanYeh** [deeptools/deepTools#1339]
The deeptools work well till I update the samtools.
I already tried update via conda.
There is the error message:
Traceback (most recent call last):
  File "/Users/lab/miniconda3/envs/bioinfo/bin/bamCompare", line 7, in <module>
    from deeptools.bamCompare import main
  File "/Users/lab/miniconda3/envs/bioinfo/lib/python3.6/site-packages/deeptools/bamCompare.py", line 9, in <module>
    from deeptools import writeBedGraph
  File "/Users/lab/miniconda3/envs/bioinfo/lib/python3.6/site-packages/deeptools/writeBedGraph.py", line 9, in <module>
    from deeptools.utilities import getCommonChrNames
  File "/Users/lab/miniconda3/envs/bioinfo/lib/python3.6/site-packages/deeptools/utilities.py", line 7, in <module>
    from deeptools import cm  # noqa: F401
  File "/Users/lab/miniconda3/envs/bioinfo/lib/python3.6/site-packages/deeptools/cm.py", line 33, in <module>
    from matplotlib import colors, colormaps as mpl_cm
ImportError: cannot import name 'colormaps'

**Comment by WardDeb** [comment]
My guess is your matplotlib version is too old.
Please try to re-install deeptools in a new conda env (py 3.6 is no longer supported).

**Comment by VihanYeh** [comment]
Thank you.
I update to Python 3.10, and the deeptools works now.
