### ISSUE TITLE
plotProfile error on matrix created with --maxThreshold set

### ISSUE THREAD

**Issue by vojtace** [deeptools/deepTools#1346]
When I run plotProfile on matrix created with the --maxThreshold set I get an error. When I don't use --maxThreshold with computeMatrix or when I downgrade numpy to 1.22.0 everything works fine.

Software version causing the error: deeptools 3.5.5, python 3.12.7 and numpy 1.26.4 (i.e. what I get from "conda install deeptools" at this moment)

The error:
Traceback (most recent call last):
  File "/home/user/miniforge3/envs/genomics/bin/plotProfile", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/miniforge3/envs/genomics/lib/python3.12/site-packages/deeptools/plotProfile.py", line 919, in main
    filterHeatmapValues(hm, hm.parameters['min threshold'], hm.parameters['max threshold'])
  File "/home/user/miniforge3/envs/genomics/lib/python3.12/site-packages/deeptools/computeMatrixOperations.py", line 430, in filterHeatmapValues
    np.warnings.filterwarnings('ignore')
    ^^^^^^^^^^^
  File "/home/user/miniforge3/envs/genomics/lib/python3.12/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'. Did you mean: 'hanning'?
Traceback (most recent call last):
  File "/usr/lib/python3.12/urllib/request.py", line 1506, in open_local_file
    stats = os.stat(localfile)

**Comment by emattei** [comment]
I want to confirm that this is reproducible because I am getting the exact same error when `--maxThreshold` is set

**Comment by rysterzhu** [comment]
I am reproducing the error using computeMatrix --maxThreshold. 
According to online comments, np.warnings has been removed from numpy.
It is recommended to manually remove or comment line 433 of computeMatrixOperations.py to skip the bug.
