### ISSUE TITLE
TypeError: sequence item 0: expected str instance, numpy.bytes_ found

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#631]
This was reported via Galaxy. If one uses `--outFileCorMatrix` (possibly only under python 3), the following error occurs:

```
Traceback (most recent call last):
  File "/export/tool_deps/_conda/envs/__deeptools@2.5.1/bin/plotCorrelation", line 11, in <module>
    main(args)
  File "/export/tool_deps/_conda/envs/__deeptools@2.5.1/lib/python3.5/site-packages/deeptools/plotCorrelation.py", line 224, in main
    corr.save_corr_matrix(args.outFileCorMatrix)
  File "/export/tool_deps/_conda/envs/__deeptools@2.5.1/lib/python3.5/site-packages/deeptools/correlation.py", line 168, in save_corr_matrix
    file_handle.write("\t'" + "'\t'".join(self.labels) + "'\n")
TypeError: sequence item 0: expected str instance, numpy.bytes_ found
```

I'm testing if this is python 3 only now.

**Comment by dpryan79** [comment]
My fix branch seems to solve the problem. I've made this live on our public Galaxy instance, but since no one else has mentioned this issue I suspect not many others are using this particular feature (or if so, they're using python 2). I'll hold off on making an actual release from this until someone else mentions bumping into it (otherwise, it'll just get fixed in deepTools 3).
