### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by brianpenghe** [deeptools/deepTools#635]
I was trying to plot metagene profiles by using this:

deepTools-2.4.2_develop/bin/computeMatrix scale-regions -S Sample.STAR.All.bigWig -R ~/genomes/danRer10-UCSC/danRer10ENSEMBL89.gtf --metagene -o test.gz

The gtf file is from UCSC which looks like this:
chr1    stdin   exon    16683985        16684084        .       +       .       gene_id "ENSDARG00000017591.10"; transcript_id "ENSDART00000145068.2"; exon_number "1"; exon_id "ENSDART00000145068.2.1"; gene_name "ENSDARG00000017591.10";
chr1    stdin   exon    16686330        16689613        .       +       .       gene_id "ENSDARG00000017591.10"; transcript_id "ENSDART00000145068.2"; exon_number "2"; exon_id "ENSDART00000145068.2.2"; gene_name "ENSDARG00000017591.10";
chr1    stdin   CDS     16686355        16689613        .       +       0       gene_id "ENSDARG00000017591.10"; transcript_id "ENSDART00000145068.2"; exon_number "2"; exon_id "ENSDART00000145068.2.2"; gene_name "ENSDARG00000017591.10";
chr1    stdin   exon    16719713        16720027        .       +       .       gene_id "ENSDARG00000017591.10"; transcript_id "ENSDART00000145068.2"; exon_number "3"; exon_id "ENSDART00000145068.2.3"; gene_name "ENSDARG00000017591.10";
chr1    stdin   CDS     16719713        16720027        .       +       2       gene_id "ENSDARG00000017591.10"; transcript_id "ENSDART00000145068.2"; exon_number "3"; exon_id "ENSDART00000145068.2.3"; gene_name "ENSDARG00000017591.10";

I got errors as follows:

Traceback (most recent call last):
  File "deepTools-2.4.2_develop/bin/computeMatrix", line 11, in <module>
    main(args)
  File "deepTools-2.4.2_develop/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 414, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "deepTools-2.4.2_develop/lib/python2.7/site-packages/deeptools/heatmapper.py", line 247, in computeMatrix
    keepExons=keepExons)
  File "deepTools-2.4.2_develop/lib/python2.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "deepTools-2.4.2_develop/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 588, in __init__
    self.parseGTF(fp, line)
  File "deepTools-2.4.2_develop/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 503, in parseGTF
    self.parseGTFexon(cols)
  File "programs/deepTools-2.4.2_develop/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 439, in parseGTFexon
    if name not in self.exons[self.labelIdx]:
IndexError: list index out of range

Any ideas?

**Comment by dpryan79** [comment]
I think this was fixed in version 2.5.0

**Comment by brianpenghe** [comment]
OK I'll get that version. Thanks!
