### ISSUE TITLE
--transcriptID in computeMatrix isn't passed down to the matrix sorting step

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#661]
This was reported by Aloy Gu in the mailing list. If you have a GTF file where you need to specify a custom `--transcriptID`, it seems that this change isn't passed down to the sorting function. The following error is produced:

```
Traceback (most recent call last):
  File "/nfs/apps/7/arch/generic/deeptools/2.5.6-py27/bin/computeMatrix", line 11, in <module>
    main(args)
  File "/nfs/apps/7/arch/generic/deeptools/2.5.6-py27/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 438, in main
    cmo.sortMatrix(hm, args.regionsFileName, args.transcriptID, args.transcript_id_designator)
  File "/nfs/apps/7/arch/generic/deeptools/2.5.6-py27/lib/python2.7/site-packages/deeptools/computeMatrixOperations.py", line 627, in sortMatrix
    hm.matrix.matrix = hm.matrix.matrix[order, :]
  File "/nfs/apps/7/arch/generic/Python/2.7.12/lib/python2.7/site-packages/numpy/ma/core.py", line 3158, in __getitem__
    dout = self.data[indx]
IndexError: arrays used as indices must be of integer (or boolean) type
```

An example command is:

```
computeMatrix scale-regions -S HD-F-327.bigwig -R Dp_geneset_OGS2.gtf -out HD-F-327.gz -b 1000 -p 8 --metagene --transcriptID mRNA
```

I'm sort of assuming that the culprit is `--transcriptID`, since changing the GTF file fixes the behavior. This needs to be confirmed locally, though.

**Comment by dpryan79** [comment]
It's been reported that `--sortRegions no` avoids this, so it's really likely that `args.transcriptID` is either not getting propagated or is getting reset somewhere.

**Comment by dpryan79** [comment]
This only happens if the `--transcriptID` option isn't lowercase, since I forgot a `.lower()` on one line. Adding that seems to fix the issue.

**Comment by dpryan79** [comment]
This is now fixed in `develop`.
