### ISSUE TITLE
plotProfile/plotHeatmap --perGroup broken with #groups > #samples

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#673]
From the mailing list:

```
I have recently updated deeptools to the latest 3.0 version and was trying to reproduce some of the plots that I have already successfully made in the past.

I would like to plot a profile for two bigwig files over a set of bed intervals.

computeMatrix scale-regions -R a.bed -S bigwig1.bw bigwig2.bw -a 10000 -b 10000 -bs 100 -m 20000 -out outmatrix

My bed file looks like this:

chr1    23100473    23102253    Gene_1    0    -
chr1    36778983    36782820    Gene_2    0    +
chr1    75385609    75432304    Gene_3    0    +

Different Groups of intervals are separated with a #Name on a new line.

I can run plotProfile -m outmatrix -o out.svg without any problems.

Although weirdly my metaplots are kind of flipped and displayed in an unusual orientation (TES first, TSS second. It always used to be, with exactly the same bed file, TSS on the left, TES on the right). But this is a minor problem.

The main problem is that when I try to run plotProfile -m outmatrix -o out.svg --perGroup I consistently get the same error:

Traceback (most recent call last):
  File "/usr/local/bin/plotProfile", line 11, in <module>
    main(args)
  File "/usr/people/me/.local/lib/python2.7/site-packages/deeptools/plotProfile.py", line 954, in main
    prof.plot_profile()
  File "/usr/people/me/.local/lib/python2.7/site-packages/deeptools/plotProfile.py", line 750, in plot_profile
    xticks, xtickslabel = self.getTicks(plot)
  File "/usr/people/me/.local/lib/python2.7/site-packages/deeptools/plotProfile.py", line 190, in getTicks
    xticks, xtickslabel = getProfileTicks(self.hm, self.reference_point_label[idx], self.start_label[idx], self.end_label[idx], idx)
IndexError: list index out of range
```

Presumably I mucked up an index somewhere. I've asked the user to provide the files so I can track this down quickly.

**Comment by dpryan79** [comment]
plotHeatmap is also broken. Realistically, anything made with `computeMatrixOperations cbind` is also broken.
