### ISSUE TITLE
Error in plotPCA command

### ISSUE THREAD

**Issue by gebenoit** [deeptools/deepTools#681]
I recently installed deepTools-3.0.1 and try to run the plotPCA command on multiBamSummary resulte file (.npz).
I got the following message:
```
### Traceback (most recent call last):
  File "/usr/local/bin/plotPCA", line 11, in <module>
    main(args)
  File "/usr/local/lib/python3.6/site-packages/deeptools/plotPCA.py", line 176, in main
    cols=args.colors)
  File "/usr/local/lib/python3.6/site-packages/deeptools/correlation.py", line 664, in plot_pca
    prop={'size': 12}, markerscale=0.9)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 497, in legend
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/legend.py", line 1402, in _parse_legend_args
    handles, labels = _get_legend_handles_labels(axs, handlers)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/legend.py", line 1360, in _get_legend_handles_labels
    and not _in_handles(handle, label)):
  File "/usr/local/lib/python3.6/site-packages/matplotlib/legend.py", line 1344, in _in_handles
    if f_h.get_facecolor() != h.get_facecolor():
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by dpryan79** [comment]
Which version of matplotlib are you getting with conda? This error tends to pop up on a couple versions.

**Comment by gebenoit** [comment]
I reinstall everything and the above error disappear. For information, the installed version of matplotlib is 2.1.1
