### ISSUE TITLE
computeGCBias should work on common chromosome names

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#695]
If a BAM and 2bit file have only partially overlapping chromosome names, then computeGCBias should work on them alone. That would prevent errors like:

```
Fatal error: Exit code 1 ()
Bam and 2bit do not have matching chromosome names:
2bit:['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chrX', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr20', 'chrY', 'chr19', 'chr22', 'chr21', 'chr6_ssto_hap7', 'chr6_mcf_hap5', 'chr6_cox_hap2', 'chr6_mann_hap4', 'chr6_apd_hap1', 'chr6_qbl_hap6', 'chr6_dbb_hap3', 'chr17_ctg5_hap1', 'chr4_ctg9_hap1', 'chr1_gl000192_random', 'chrUn_gl000225', 'chr4_gl000194_random', 'chr4_gl000193_random', 'chr9_gl000200_random', 'chrUn_gl000222', 'chrUn_gl000212', 'chr7_gl000195_random', 'chrUn_gl000223', 'chrUn_gl000224', 'chrUn_gl000219', 'chr17_gl000205_random', 'chrUn_gl000215', 'chrUn_gl000216', 'chrUn_gl000217', 'chr9_gl000199_random', 'chrUn_gl000211', 'chrUn_gl000213', 'chrUn_gl000220', 'chrUn_gl000218', 'chr19_gl000209_random', 'chrUn_gl000221', 'chrUn_gl000214', 'chrUn_gl000228', 'chrUn_gl000227', 'chr1_gl000191_random', 'chr19_gl000208_random', 'chr9_gl000198_random', 'chr17_gl000204_random', 'chrUn_gl000233', 'chrUn_gl000237', 'chrUn_gl000230', 'chrUn_gl000242', 'chrUn_gl000243', 'chrUn_gl000241', 'chrUn_gl000236', 'chrUn_gl000240', 'chr17_gl000206_random', 'chrUn_gl000232', 'chrUn_gl000234', 'chr11_gl000202_random', 'chrUn_gl000238', 'chrUn_gl000244', 'chrUn_gl000248', 'chr8_gl000196_random', 'chrUn_gl000249', 'chrUn_gl000246', 'chr17_gl000203_random', 'chr8_gl000197_random', 'chrUn_gl000245', 'chrUn_gl000247', 'chr9_gl000201_random', 'chrUn_gl000235', 'chrUn_gl000239', 'chr21_gl000210_random', 'chrUn_gl000231', 'chrUn_gl000229', 'chrM', 'chrUn_gl000226', 'chr18_gl000207_random']

bam:('chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM', 'chr1_KI270706v1_random', 'chr1_KI270707v1_random', 'chr1_KI270708v1_random', 'chr1_KI270709v1_random', 'chr1_KI270710v1_random', 'chr1_KI270711v1_random', 'chr1_KI270712v1_random', 'chr1_KI270713v1_random', 'chr1_KI270714v1_random', 'chr2_KI270715v1_random', 'chr2_KI270716v1_random', 'chr3_GL000221v1_random', 'chr4_GL000008v2_random', 'chr5_GL000208v1_random', 'chr9_KI270717v1_random', 'chr9_KI270718v1_random', 'chr9_KI270719v1_random', 'chr9_KI270720v1_random', 'chr11_KI270721v1_random', 'chr14_GL000009v2_random', 'chr14_GL000225v1_random', 'chr14_KI270722v1_random', 'chr14_GL000194v1_random', 'chr14_KI270723v1_random', 'chr14_KI270724v1_random', 'chr14_KI270725v1_random', 'chr14_KI270726v1_random', 'chr15_KI270727v1_random', 'chr16_KI270728v1_random', 'chr17_GL000205v2_random', 'chr17_KI270729v1_random', 'chr17_KI270730v1_random', 'chr22_KI270731v1_random', 'chr22_KI270732v1_random', 'chr22_KI270733v1_random', 'chr22_KI270734v1_random', 'chr22_KI270735v1_random', 'chr22_KI270736v1_random', 'chr22_KI270737v1_random', 'chr22_KI270738v1_random', 'chr22_KI270739v1_random', 'chrY_KI270740v1_random', 'chrUn_KI270302v1', 'chrUn_KI270304v1', 'chrUn_KI270303v1', 'chrUn_KI270305v1', 'chrUn_KI270322v1', 'chrUn_KI270320v1', 'chrUn_KI270310v1', 'chrUn_KI270316v1', 'chrUn_KI270315v1', 'chrUn_KI270312v1', 'chrUn_KI270311v1', 'chrUn_KI270317v1', 'chrUn_KI270412v1', 'chrUn_KI270411v1', 'chrUn_KI270414v1', 'chrUn_KI270419v1', 'chrUn_KI270418v1', 'chrUn_KI270420v1', 'chrUn_KI270424v1', 'chrUn_KI270417v1', 'chrUn_KI270422v1', 'chrUn_KI270423v1', 'chrUn_KI270425v1', 'chrUn_KI270429v1', 'chrUn_KI270442v1', 'chrUn_KI270466v1', 'chrUn_KI270465v1', 'chrUn_KI270467v1', 'chrUn_KI270435v1', 'chrUn_KI270438v1', 'chrUn_KI270468v1', 'chrUn_KI270510v1', 'chrUn_KI270509v1', 'chrUn_KI270518v1', 'chrUn_KI270508v1', 'chrUn_KI270516v1', 'chrUn_KI270512v1', 'chrUn_KI270519v1', 'chrUn_KI270522v1', 'chrUn_KI270511v1', 'chrUn_KI270515v1', 'chrUn_KI270507v1', 'chrUn_KI270517v1', 'chrUn_KI270529v1', 'chrUn_KI270528v1', 'chrUn_KI270530v1', 'chrUn_KI270539v1', 'chrUn_KI270538v1', 'chrUn_KI270544v1', 'chrUn_KI270548v1', 'chrUn_KI270583v1', 'chrUn_KI270587v1', 'chrUn_KI270580v1', 'chrUn_KI270581v1', 'chrUn_KI270579v1', 'chrUn_KI270589v1', 'chrUn_KI270590v1', 'chrUn_KI270584v1', 'chrUn_KI270582v1', 'chrUn_KI270588v1', 'chrUn_KI270593v1', 'chrUn_KI270591v1', 'chrUn_KI270330v1', 'chrUn_KI270329v1', 'chrUn_KI270334v1', 'chrUn_KI270333v1', 'chrUn_KI270335v1', 'chrUn_KI270338v1', 'chrUn_KI270340v1', 'chrUn_KI270336v1', 'chrUn_KI270337v1', 'chrUn_KI270363v1', 'chrUn_KI270364v1', 'chrUn_KI270362v1', 'chrUn_KI270366v1', 'chrUn_KI270378v1', 'chrUn_KI270379v1', 'chrUn_KI270389v1', 'chrUn_KI270390v1', 'chrUn_KI270387v1', 'chrUn_KI270395v1', 'chrUn_KI270396v1', 'chrUn_KI270388v1', 'chrUn_KI270394v1', 'chrUn_KI270386v1', 'chrUn_KI270391v1', 'chrUn_KI270383v1', 'chrUn_KI270393v1', 'chrUn_KI270384v1', 'chrUn_KI270392v1', 'chrUn_KI270381v1', 'chrUn_KI270385v1', 'chrUn_KI270382v1', 'chrUn_KI270376v1', 'chrUn_KI270374v1', 'chrUn_KI270372v1', 'chrUn_KI270373v1', 'chrUn_KI270375v1', 'chrUn_KI270371v1', 'chrUn_KI270448v1', 'chrUn_KI270521v1', 'chrUn_GL000195v1', 'chrUn_GL000219v1', 'chrUn_GL000220v1', 'chrUn_GL000224v1', 'chrUn_KI270741v1', 'chrUn_GL000226v1', 'chrUn_GL000213v1', 'chrUn_KI270743v1', 'chrUn_KI270744v1', 'chrUn_KI270745v1', 'chrUn_KI270746v1', 'chrUn_KI270747v1', 'chrUn_KI270748v1', 'chrUn_KI270749v1', 'chrUn_KI270750v1', 'chrUn_KI270751v1', 'chrUn_KI270752v1', 'chrUn_KI270753v1', 'chrUn_KI270754v1', 'chrUn_KI270755v1', 'chrUn_KI270756v1', 'chrUn_KI270757v1', 'chrUn_GL000214v1', 'chrUn_KI270742v1', 'chrUn_GL000216v2', 'chrUn_GL000218v1', 'chrEBV')

Using the following common chromosomes between bam chromosome names and 2bit chromosome names:
chr19
chr8
chr6
chr5
chr1
chr22
chr17
chr13
chr7
chr20
chr18
chr21
chr14
chrM
chr15
chr4
chr16
chr10
chrY
chr11
chr3
chr12
chrX
chr2
chr9
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/site-packages/deeptools/computeGCBias.py", line 196, in countReadsPerGC_wrapper
    return countReadsPerGC_worker(*args)
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/site-packages/deeptools/computeGCBias.py", line 207, in countReadsPerGC_worker
    chromNameBit = chrNameBamToBit[chromNameBam]
KeyError: 'chrUn_KI270538v1'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/bin/computeGCBias", line 11, in <module>
    main(args)
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/site-packages/deeptools/computeGCBias.py", line 727, in main
    region=args.region)
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/site-packages/deeptools/computeGCBias.py", line 485, in countReadsPerGC
    region=region)
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/export/tool_deps/_conda/envs/mulled-v1-1693e8dc8ba4da0bc1cdadbdebcf16bd6a032a9f43e821b35aaa2b2df4a2c618/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: 'chrUn_KI270538v1'
```

**Comment by dpryan79** [comment]
This is now fixed in `develop`.
