### ISSUE TITLE
multiBamSummary Error

### ISSUE THREAD

**Issue by Rruhel** [deeptools/deepTools#722]
I am trying to find correlation between my 8 bam files for which all sam files generated by Hisat2 were converted to bam and were indexed. I get the following error when I ran multiBamSummary in command line.

-----------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/deeptools/utilities.py", line 179, in get_chrom_and_size
    return [(x, y) for x, y in zip(bam_handler.references, bam_handler.lengths)]
  File "pysam/libcalignmentfile.pyx", line 1898, in pysam.libcalignmentfile.AlignmentFile.references.__get__ (pysam/libcalignmentfile.c:22714)
  File "pysam/libcalignmentfile.pyx", line 360, in pysam.libcalignmentfile.AlignmentHeader.references.__get__ (pysam/libcalignmentfile.c:7465)
  File "pysam/libcutils.pyx", line 134, in pysam.libcutils.charptr_to_str (pysam/libcutils.c:3215)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 2: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/multiBamSummary", line 13, in <module>
    main(args)
  File "/usr/local/lib/python3.6/site-packages/deeptools/multiBamSummary.py", line 233, in main
    num_reads_per_bin = c.run(allArgs=args)
  File "/usr/local/lib/python3.6/site-packages/deeptools/countReadsPerBin.py", line 303, in run
    chromsizes, non_common = deeptools.utilities.getCommonChrNames(bamFilesHandles, verbose=self.verbose)
  File "/usr/local/lib/python3.6/site-packages/deeptools/utilities.py", line 188, in getCommonChrNames
    common_chr = set(get_chrom_and_size(bamFileHandles[0]))
  File "/usr/local/lib/python3.6/site-packages/deeptools/utilities.py", line 181, in get_chrom_and_size
    return [(k, v) for k, v in bam_handler.chroms().items()]
AttributeError: 'pysam.libcsamfile.Samfile' object has no attribute 'chroms'
---------

Is there any issue with deep tools installation? 
Being a beginner in bioinformatics, would appreciate any help.

**Comment by dpryan79** [comment]
What version of pysam do you have installed (`pip3 freeze | grep pysam`)?

**Comment by Rruhel** [comment]
It's pysam==0.14.1

**Comment by dpryan79** [comment]
You seem to have some installation issue with pysam, I suggest you simply use `conda` instead or try removing and reinstalling pysam.
