### ISSUE TITLE
plotPCA fails with error

### ISSUE THREAD

**Issue by steffenheyne** [deeptools/deepTools#738]
Traceback (most recent call last):
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/bin/plotPCA", line 12, in <module>
    main(args)
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/lib/python3.6/site-packages/deeptools/plotPCA.py", line 176, in main
    cols=args.colors)
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/lib/python3.6/site-packages/deeptools/correlation.py", line 700, in plot_pca
    plt.tight_layout()
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1366, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/lib/python3.6/site-packages/matplotlib/figure.py", line 2276, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/lib/python3.6/site-packages/matplotlib/figure.py", line 2088, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/package/anaconda3/envs/da3f539f8a6dbc681251fbd96f0832f7/lib/python3.6/site-packages/matplotlib/figure.py", line 241, in update
    raise ValueError('left cannot be >= right')
ValueError: left cannot be >= right

deepTools version 3.1.0 

```
plotPCA -in deepTools_qc/multiBamSummary/read_coverage.bins.npz 
--plotFile deepTools_qc/plotPCA/PCA.read_coverage.png --transpose 
--outFileNameData deepTools_qc/plotPCA/PC A.read_coverage.tsv 
-T 'PCA of fragment coverage'
```

**Comment by dpryan79** [comment]
We need to change the default width to 10cm in version 3.1.1

**Comment by dpryan79** [comment]
I've changed the default to 10 in the develop branch and that will appear (shortly) in version 3.1.1

**Comment by cgirardot** [comment]
I have the same error in galaxy (Galaxy Version 3.0.2.0). Changed the width from 5 to 10 according to comments here but it still fails.

**Comment by dpryan79** [comment]
Certainly, I'll reopen this as a reminder.
