### ISSUE TITLE
AttributeError: 'module' object has no attribute 'to_hex'

### ISSUE THREAD

**Issue by simjbaum** [deeptools/deepTools#750]
Dear all,
thank you for coding such a great tool, unfortunately I ran into a problem, could you please help me with that?

plotHeatmap -m ./testFOXA1_computeMatrix -o test_Heatmap --colorMap YlGnBu
Traceback (most recent call last):
  File "/usr/local/bin/plotHeatmap", line 11, in <module>
    main(args)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/plotHeatmap.py", line 836, in main
    interpolation_method=args.interpolationMethod)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/plotHeatmap.py", line 545, in plotMatrix
    ax_list = addProfilePlot(hm, plt, fig, grids, iterNum, iterNum2, perGroup, averageType, yAxisLabel, color_list, yMin, yMax, None, None, colorbar_position, label_rotation)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/plotHeatmap.py", line 155, in addProfilePlot
    plot_type='simple')
  File "/usr/local/lib/python2.7/dist-packages/deeptools/heatmapper_utilities.py", line 69, in plot_single
    color = pltcolors.to_hex(color, keep_alpha=True)
AttributeError: 'module' object has no attribute 'to_hex'

deeptools 3.0.2
Python 2.7.12

**Comment by dpryan79** [comment]
What version of matplotlib do you have installed?

**Comment by simjbaum** [comment]
>>> import matplotlib as mpl
>>> print mpl.__version__
1.5.1

**Comment by dpryan79** [comment]
DeepTools requires at least version 2.1.2.

**Comment by simjbaum** [comment]
thank you very much for the fast replies and help (and sorry that I havent checked these requirements)!
