### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by simjbaum** [deeptools/deepTools#751]
Hi,
I got following error after running plotHeatmap (after upgrading the matplotlib - and "solving" this)

>>> import matplotlib
>>> matplotlib.__version__
'2.2.3'

deeptools 3.1.1
Python 3.5.2

:plotHeatmap -m ./testFOXA1 -o test_Heatmap

Traceback (most recent call last):
  File "/home/ggayq/.local/bin/plotHeatmap", line 5, in <module>
    from deeptools.plotHeatmap import main
  File "/home/ggayq/.local/lib/python3.5/site-packages/deeptools/plotHeatmap.py", line 18, in <module>
    import plotly.offline as py
  File "/home/ggayq/.local/lib/python3.5/site-packages/plotly/__init__.py", line 31, in <module>
    from plotly import (plotly, dashboard_objs, graph_objs, grid_objs, tools,
  File "/home/ggayq/.local/lib/python3.5/site-packages/plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "/home/ggayq/.local/lib/python3.5/site-packages/plotly/plotly/plotly.py", line 32, in <module>
    from plotly.basedatatypes import BaseTraceType, BaseFigure, BaseLayoutType
  File "/home/ggayq/.local/lib/python3.5/site-packages/plotly/basedatatypes.py", line 12, in <module>
    from . import offline as pyo
  File "/home/ggayq/.local/lib/python3.5/site-packages/plotly/offline/__init__.py", line 6, in <module>
    from . offline import (
  File "/home/ggayq/.local/lib/python3.5/site-packages/plotly/offline/offline.py", line 11, in <module>
    from pkg_resources import resource_string
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

Thanks for your help in advance, 
best wishes,
Simon

**Comment by simjbaum** [comment]
Good morning,


>>> import plotly
>>> print(plotly.__version__)
3.1.1


best,
Simon

**Comment by dpryan79** [comment]
I can't reproduce this issue, it's likely that you have a problem with your python installation.
