### ISSUE TITLE
for deepTools 3.1.2 plotly minimum version is 2.0.0

### ISSUE THREAD

**Issue by ebirn** [deeptools/deepTools#755]
Hi,

The minimum required version of plotly for deepTools 3.1.2 is 2.0.0

The requirements file references 1.9.0:
https://github.com/deeptools/deepTools/blob/3024062b63fdc502b46e4f328083493c2274182a/requirements.txt#L8

I believe the relevant commit upstream is https://github.com/plotly/plotly.py/commit/70e721180b721f0339a8aa6a1ad73406d904f553#diff-3a54ebd2854b468894e7300ed450ab98
(which is in version tags 2.0.0 and above, I also tested it with 2.0.0 of plotly and it works for me)

error trace with plotly 1.9.0 (for both python 2.7 and 3.6):
Traceback (most recent call last):
  File "/net/gmi.oeaw.ac.at/software/mendel/intel-x86_64-sandybridge-avx/software/deepTools/3.1.2-foss-2018a-Python-2.7.14/bin/plotPCA", line 5, in <module>
    from deeptools.plotPCA import main
  File "/net/gmi.oeaw.ac.at/software/mendel/intel-x86_64-sandybridge-avx/software/deepTools/3.1.2-foss-2018a-Python-2.7.14/lib/python2.7/site-packages/deeptools/plotPCA.py", line 11, in <module>
    from deeptools.correlation import Correlation
  File "/net/gmi.oeaw.ac.at/software/mendel/intel-x86_64-sandybridge-avx/software/deepTools/3.1.2-foss-2018a-Python-2.7.14/lib/python2.7/site-packages/deeptools/correlation.py", line 20, in <module>
    import plotly.figure_factory as ff
ImportError: No module named figure_factory

Best,
Erich

**Comment by dpryan79** [comment]
I guess 2.0 came out while I was implementing the plotly stuff, since I originally started testing things with 1.9.0. That requirement obviously needs to be bumped though!

**Comment by dpryan79** [comment]
This is now fixed in the `develop` branch and will be present in the next release.
