### ISSUE TITLE
computeMatrix: ValueError

### ISSUE THREAD

**Issue by JihedC** [deeptools/deepTools#769]
Hi everyone,

I discovered deeptools recently and I find it amazing, I just have one issue at the very end of my pipeline. I am using deep tools within a Snakemake pipeline, just for you to know, but I don't think this is the problem here. I have an issue when I use the `computeMatrix reference-point` using the `gene_model.gff` of the version 3.2 of the tomato genome, I get a strange error.

My issue is a bit of the same as this [one]( #66 ). However it was 4 years ago and I don't know if it was fixed.

I am using these versions : 
* deeptools 3.1.2
* Python 3.5.1 :: Continuum Analytics, Inc.

This is the command I used:
`computeMatrix reference-point --referencePoint TSS -S results/bamcompare/log2_ChIP2_ChIP4.bamcompare.bw -R temp/gene_model.gff -o results/computematrix/ChIP2_ChIP4.TSS.gz`

This is the error I got : 

```
Traceback (most recent call last):
  File "/anaconda3/envs/bigwig/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/anaconda3/envs/bigwig/lib/python3.5/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/anaconda3/envs/bigwig/lib/python3.5/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "/anaconda3/envs/bigwig/lib/python3.5/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/anaconda3/envs/bigwig/lib/python3.5/site-packages/deeptoolsintervals/parse.py", line 597, in __init__
    self.parseBED(fp, line, 6, labelColumn)
  File "/anaconda3/envs/bigwig/lib/python3.5/site-packages/deeptoolsintervals/parse.py", line 317, in parseBED
    self.parseBEDcore(line, ncols)
  File "/anaconda3/envs/bigwig/lib/python3.5/site-packages/deeptoolsintervals/parse.py", line 225, in parseBEDcore
    if int(cols[1]) < 0:
ValueError: invalid literal for int() with base 10: 'maker_ITAG'
```

It seems that there is an issue with the GFF file, so I am wondering if there is an issue with the GFF. It's the first time I do ChIP-seq analysis and don't know so much about the file format required. This is how my GFF file looks like: 

```
##gff-version 3
##sequence-region   SL3.0ch00 1 20852292
##sequence-region   SL3.0ch01 1 98455869
##sequence-region   SL3.0ch02 1 55977580
##sequence-region   SL3.0ch03 1 72290146
##sequence-region   SL3.0ch04 1 66557038
##sequence-region   SL3.0ch05 1 66723567
##sequence-region   SL3.0ch06 1 49794276
##sequence-region   SL3.0ch07 1 68175699
##sequence-region   SL3.0ch08 1 65987440
##sequence-region   SL3.0ch09 1 72906345
##sequence-region   SL3.0ch10 1 65633393
##sequence-region   SL3.0ch11 1 56597135
##sequence-region   SL3.0ch12 1 68126176
SL3.0ch00       maker_ITAG      gene    16480   17940   .       +       .       ID=gene:Solyc00g005000.3;Alias=Solyc00g005000;Name=Solyc00g005000.3;length=1460
SL3.0ch00       maker_ITAG      mRNA    16480   17940   .       +       .       ID=mRNA:Solyc00g005000.3.1;Parent=gene:Solyc00g005000.3;Name=Solyc00g005000.3.1;_AED=0.08;Note=Eukaryotic aspartyl protease family protein (AHRD V3.3 *** AT3G20015.1);Dbxref=InterPro:IPR001461;Ontology_term=GO:0004190,GO:0006508
SL3.0ch00       maker_ITAG      exon    16480   16794   .       +       .       ID=exon:Solyc00g005000.3.1.1;Parent=mRNA:Solyc00g005000.3.1
SL3.0ch00       maker_ITAG      CDS     16480   16794   .       +       0       ID=CDS:Solyc00g005000.3.1.1;Parent=mRNA:Solyc00g005000.3.1
SL3.0ch00       maker_ITAG      exon    16879   17940   .       +       .       ID=exon:Solyc00g005000.3.1.2;Parent=mRNA:Solyc00g005000.3.1
SL3.0ch00       maker_ITAG      CDS     16879   17940   .       +       0       ID=CDS:Solyc00g005000.3.1.2;Parent=mRNA:Solyc00g005000.3.1
###
SL3.0ch00       maker_ITAG      gene    548344  551581  .       +       .       ID=gene:Solyc00g005040.3;Alias=Solyc00g005040;Name=Solyc00g005040.3;length=3237
SL3.0ch00       maker_ITAG      mRNA    548344  551581  .       +       .       ID=mRNA:Solyc00g005040.3.1;Parent=gene:Solyc00g005040.3;Name=Solyc00g005040.3.1;_AED=0.20;Note=Potassium channel (AHRD V3.3 *-* D0EM91_9ROSI);Dbxref=InterPro:IPR000595,Pfam:PF00027
SL3.0ch00       maker_ITAG      exon    548344  548703  .       +       .       ID=exon:Solyc00g005040.3.1.1;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      five_prime_UTR  548344  548703  .       +       .       ID=five_prime_UTR:Solyc00g005040.3.1.0;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      exon    549226  549319  .       +       .       ID=exon:Solyc00g005040.3.1.2;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      five_prime_UTR  549226  549319  .       +       .       ID=five_prime_UTR:Solyc00g005040.3.1.1;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      exon    550857  550944  .       +       .       ID=exon:Solyc00g005040.3.1.3;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      five_prime_UTR  550857  550944  .       +       .       ID=five_prime_UTR:Solyc00g005040.3.1.2;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      five_prime_UTR  551033  551041  .       +       .       ID=five_prime_UTR:Solyc00g005040.3.1.3;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      exon    551033  551131  .       +       .       ID=exon:Solyc00g005040.3.1.4;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      CDS     551042  551131  .       +       0       ID=CDS:Solyc00g005040.3.1.1;Parent=mRNA:Solyc00g005040.3.1
SL3.0ch00       maker_ITAG      exon    551217  551249  .       +       .       ID=exon:Solyc00g005040.3.1.5;Parent=mRNA:Solyc00g005040.3.1

```

I hope this can help to solve the issue! 
Thanks!

**Comment by dpryan79** [comment]
Can you post a link to that GFF? I was hoping to push out a new release tonight and would like to fix this if the bug is in DeepTools and not the GFF file. I should note that we only formally support GTF and BED files, as GFF files can be a real mess.

**Comment by JihedC** [comment]
Here is the link to the:
ftp://ftp.solgenomics.net/tomato_genome/annotation/ITAG3.2_release/ITAG3.2_gene_models.gff

**Comment by dpryan79** [comment]
Thanks @JihedC, I'll take a look real quick!

**Comment by JihedC** [comment]
Thanks @dpryan79 for your quick replies!

**Comment by dpryan79** [comment]
Yeah, that GFF file is a pain to deal with and there's no way to make it compatible with deepTools. I've converted that GTF file to a smaller more standardized GTF file that you can use instead. [Here's a link to that](https://drive.google.com/open?id=1bZaGm3A0h-DFomjQDnFwW09UJtrHudsO)

In case you want to further modify that, here's the script I just threw together to convert the GFF file to a GTF file:

```
#!/usr/bin/env python

f = open("ITAG3.2_gene_models.gff")
of = open("ITAG3.2_gene_models.gtf", "w")

keep = set(["gene", "transcript", "exon"])
for line in f:
    if line.startswith("#"):
        continue
    cols = line.split("\t")
    if cols[2] == "mRNA":
        cols[2] = "transcript"
    if cols[2] not in keep:
        continue

    attribs = cols[8].split(";")
    attribs = [x.replace("=", "\t").split("\t") for x in attribs]
    newAttribs = {}
    for t in attribs:
        if t[0] == "ID":
            _, ID = t[1].split(":")
            if cols[2] == "gene":
                newAttribs['gene_id'] = ID
            elif cols[2] == "transcript":
                newAttribs['transcript_id'] = ID
                x = ID.rindex(".")
                newAttribs['gene_id'] = ID[:x]
            elif cols[2] == "exon":
                x = ID.rindex(".")
                ID = ID[:x]
                newAttribs['transcript_id'] = ID
                x = ID.rindex(".")
                ID = ID[:x]
                newAttribs['gene_id'] = ID
    cols[8] = " ".join("{} \"{}\";".format(x, y) for x, y in newAttribs.items())
    of.write("\t".join(cols))
    of.write("\n")
f.close()
of.close()
```

**Comment by JihedC** [comment]
Thanks a lot! It works now!
