### ISSUE TITLE
plotProfile error

### ISSUE THREAD

**Issue by Sam7474** [deeptools/deepTools#786]
deeptools --version: deeptools 3.1.3
python --version: Python 2.7.14 :: Anaconda custom (64-bit)

plotProfile --matrixFile centred_motifs_sigresults_2500.mat.gz --outFileName centred_motifs_sigresults_2500-test.png --refPointLabel 'centre' --numPlotsPerRow 4 --perGroup

Traceback (most recent call last):
  File "~/anaconda2/bin/plotProfile", line 12, in <module>
    main(args)
  File "~/anaconda2/lib/python2.7/site-packages/deeptools/plotProfile.py", line 965, in main
    prof.plot_profile()
  File "~/anaconda2/lib/python2.7/site-packages/deeptools/plotProfile.py", line 740, in plot_profile
    plot_type=self.plot_type)
  File "~/anaconda2/lib/python2.7/site-packages/deeptools/heatmapper_utilities.py", line 69, in plot_single
    color = pltcolors.to_hex(color, keep_alpha=True)
AttributeError: 'module' object has no attribute 'to_hex'

**Comment by vivekbhr** [comment]
seems to be same as #750
