### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SichongP** [deeptools/deepTools#787]
There was a same issue (#635 ) but it seems to have been resolved by updating to version 2.5.
However, I'm running into the same issue with version 3.0.1 (with python version 3.6.7)

command used:
```
computeMatrix reference-point -S *.bw -R *.gtf --beforeRegionStartLength 3000 --afterRegionStartLength 3000 -out *.mat.gz -p 4 --s
amplesLabel CTCF
```
The output is as follows:
```
Traceback (most recent call last):
  File "/home/pengsc/miniconda3/envs/deeptools/bin/computeMatrix", line 13, in <module>
    main(args)
  File "/home/pengsc/miniconda3/envs/deeptools/lib/python3.6/site-packages/deeptools/computeMatrix.py", line 419, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/home/pengsc/miniconda3/envs/deeptools/lib/python3.6/site-packages/deeptools/heatmapper.py", line 260, in computeMatrix
    keepExons=keepExons)
  File "/home/pengsc/miniconda3/envs/deeptools/lib/python3.6/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/home/pengsc/miniconda3/envs/deeptools/lib/python3.6/site-packages/deeptoolsintervals/parse.py", line 593, in __init__
    self.parseGTF(fp, line)
  File "/home/pengsc/miniconda3/envs/deeptools/lib/python3.6/site-packages/deeptoolsintervals/parse.py", line 508, in parseGTF
    self.parseGTFexon(cols)
  File "/home/pengsc/miniconda3/envs/deeptools/lib/python3.6/site-packages/deeptoolsintervals/parse.py", line 444, in parseGTFexon
    if name not in self.exons[self.labelIdx]:
IndexError: list index out of range
```

First few lines of my gtf file:
```
chr1    unknown exon    132227  132643  .       -       .       gene_id "CYP2E1"; gene_name "CYP2E1"; p_id "P320"; transcript_id "NM_001111303"; tss_id "TSS210";
chr1    unknown stop_codon      132459  132461  .       -       .       gene_id "CYP2E1"; gene_name "CYP2E1"; p_id "P320"; transcript_id "NM_001111303"; tss_id "TSS210";
chr1    unknown CDS     132462  132643  .       -       0       gene_id "CYP2E1"; gene_name "CYP2E1"; p_id "P320"; transcript_id "NM_001111303"; tss_id "TSS210";
chr1    unknown CDS     133462  133541  .       -       2       gene_id "CYP2E1"; gene_name "CYP2E1"; p_id "P320"; transcript_id "NM_001111303"; tss_id "TSS210";
```
I have checked the gtf file to make sure all entries have exactly 9 columns.
I also tried --transcript_id_designator or --transcriptID option to specify key but got the same result.

**Comment by vivekbhr** [comment]
Do you have more than 1 GTF files being used in the command?

**Comment by SichongP** [comment]
> Do you have more than 1 GTF files being used in the command?

It was only one file. I replaced absolute paths in the command b/c they were too long. Didn't realize it could be confusing. Sorry about that!

**Comment by SichongP** [comment]
The gtf file is missing "gene" and "transcript" entries.
