### ISSUE TITLE
`Invalid Interval Bounds` Error in multiBigwigSummary

### ISSUE THREAD

**Issue by anamayshetty** [deeptools/deepTools#788]
Hi,

I am working with multiBigWigSummary and am getting the following error:

```
$ multiBigwigSummary BED-file --bwfiles input_bigwig_files/FOXA1_2480_T.rep1_treat_pileup.bw --outFileName foxa1_dry_run_output.npz --BED dry_run_foxa1_peaks.bed --outRawCounts foxa1_dry_run_output.tab

Traceback (most recent call last):
  File "/bcb/agusevlab/miniconda2/bin/multiBigwigSummary", line 14, in <module>
    main(args)
  File "/bcb/agusevlab/miniconda2/lib/python2.7/site-packages/deeptools/multiBigwigSummary.py", line 262, in main
    allArgs=args)
  File "/bcb/agusevlab/miniconda2/lib/python2.7/site-packages/deeptools/getScorePerBigWigBin.py", line 268, in getScorePerBin
    transcript_id_designator=transcript_id_designator)
  File "/bcb/agusevlab/miniconda2/lib/python2.7/site-packages/deeptools/mapReduce.py", line 146, in mapReduce
    res = list(map(func, TASKS))
  File "/bcb/agusevlab/miniconda2/lib/python2.7/site-packages/deeptools/getScorePerBigWigBin.py", line 18, in countReadsInRegions_wrapper
    return countFragmentsInRegions_worker(*args)
  File "/bcb/agusevlab/miniconda2/lib/python2.7/site-packages/deeptools/getScorePerBigWigBin.py", line 107, in countFragmentsInRegions_worker
    score = bwh.stats(chrom, exon[0], exon[1])
RuntimeError: Invalid interval bounds!
```
This problem appears to only be occurring when in BED-file mode, and bins mode successfully produces output without any errors being thrown up by the program. 
The bed file has 4 tab-separated columns; no starts/stops < 0; has been successfully used with bedtools. I am on an hg19 build. 

```
chr1	9378	11583	chr1-10378:10583
chr1	234663	236988	chr1-235663:235988
chr1	525459	527782	chr1-526459:526782
chr1	564857	567103	chr1-565857:566103
chr1	566449	568715	chr1-567449:567715
chr1	568801	571060	chr1-569801:570060
chr1	712872	715714	chr1-713872:714714
chr1	714121	716308	chr1-715121:715308
chr1	724851	727053	chr1-725851:726053
chr1	725832	728098	chr1-726832:727098
```

I am on `deeptools 3.1.3` and `Python 2.7.14 :: Anaconda, Inc.`

Regards,

Anamay

**Comment by anamayshetty** [comment]
Doesn't look like it to me- I just went and extracted all of the chromosomes from my bigwig file to a wig file and looks like all 22+X+Y+M are present.

I used the following command setup:

```
seq 1 22 | while read line; do bigWigToWig input_bigwig_files/FOXA1_2480_T.rep1_treat_pileup.bw FOXA1_2480_T.chr${line}.txt -chrom=chr${line}; done

echo X Y M | tr " " "\n" | while read line; do bigWigToWig input_bigwig_files/FOXA1_2480_T.rep1_treat_pileup.bw FOXA1_2480_T.chr${line}.txt -chrom=chr${line}; done
```

```
==> FOXA1_2480_T.chr10.txt <==
#bedGraph section chr10:0-156766

==> FOXA1_2480_T.chr11.txt <==
#bedGraph section chr11:0-208724

==> FOXA1_2480_T.chr12.txt <==
#bedGraph section chr12:0-189805

==> FOXA1_2480_T.chr13.txt <==
#bedGraph section chr13:0-19280644

==> FOXA1_2480_T.chr14.txt <==
#bedGraph section chr14:0-19021475

==> FOXA1_2480_T.chr15.txt <==
#bedGraph section chr15:0-20058953

==> FOXA1_2480_T.chr16.txt <==
#bedGraph section chr16:0-134747

==> FOXA1_2480_T.chr17.txt <==
#bedGraph section chr17:0-60695

==> FOXA1_2480_T.chr18.txt <==
#bedGraph section chr18:0-92745

==> FOXA1_2480_T.chr19.txt <==
#bedGraph section chr19:0-275026

==> FOXA1_2480_T.chr1.txt <==
#bedGraph section chr1:0-714343

==> FOXA1_2480_T.chr20.txt <==
#bedGraph section chr20:0-151871

==> FOXA1_2480_T.chr21.txt <==
#bedGraph section chr21:0-9437113

==> FOXA1_2480_T.chr22.txt <==
#bedGraph section chr22:0-16313430

==> FOXA1_2480_T.chr2.txt <==
#bedGraph section chr2:0-50258

==> FOXA1_2480_T.chr3.txt <==
#bedGraph section chr3:0-106127

==> FOXA1_2480_T.chr4.txt <==
#bedGraph section chr4:0-47094

==> FOXA1_2480_T.chr5.txt <==
#bedGraph section chr5:0-47549

==> FOXA1_2480_T.chr6.txt <==
#bedGraph section chr6:0-244942

==> FOXA1_2480_T.chr7.txt <==
#bedGraph section chr7:0-129939

==> FOXA1_2480_T.chr8.txt <==
#bedGraph section chr8:0-224081

==> FOXA1_2480_T.chr9.txt <==
#bedGraph section chr9:0-198293

==> FOXA1_2480_T.chrM.txt <==
#bedGraph section chrM:0-1829

==> FOXA1_2480_T.chrX.txt <==
#bedGraph section chrX:0-2787310

==> FOXA1_2480_T.chrY.txt <==
#bedGraph section chrY:0-2742091
```

```
   2353792 FOXA1_2480_T.chr10.txt
   2436291 FOXA1_2480_T.chr11.txt
   2571119 FOXA1_2480_T.chr12.txt
   1325590 FOXA1_2480_T.chr13.txt
   1826213 FOXA1_2480_T.chr14.txt
    988483 FOXA1_2480_T.chr15.txt
   1066608 FOXA1_2480_T.chr16.txt
   1419925 FOXA1_2480_T.chr17.txt
    975400 FOXA1_2480_T.chr18.txt
   1047164 FOXA1_2480_T.chr19.txt
   3799952 FOXA1_2480_T.chr1.txt
   1106804 FOXA1_2480_T.chr20.txt
    717615 FOXA1_2480_T.chr21.txt
    553567 FOXA1_2480_T.chr22.txt
   4103693 FOXA1_2480_T.chr2.txt
   3997340 FOXA1_2480_T.chr3.txt
   2479470 FOXA1_2480_T.chr4.txt
   2988455 FOXA1_2480_T.chr5.txt
   3157388 FOXA1_2480_T.chr6.txt
   2881421 FOXA1_2480_T.chr7.txt
   3309092 FOXA1_2480_T.chr8.txt
   2497848 FOXA1_2480_T.chr9.txt
      6199 FOXA1_2480_T.chrM.txt
   1408177 FOXA1_2480_T.chrX.txt
    153272 FOXA1_2480_T.chrY.txt
  49170878 total
```

**Comment by dpryan79** [comment]
Can you make the bigWig and BED files available? That will make this easier to debug.

**Comment by anamayshetty** [comment]
Yes I can.
[This link will take you to the bigwig and bed file on Dropbox.](https://www.dropbox.com/sh/yh0pdjlpflxglu4/AABgU3lRnhtmuZDZMHgsQujGa?dl=0)

**Comment by dpryan79** [comment]
The following entries exceed the chromosome bounds:

    chr17        81193948    81196099
    chrM               13318         17528

If you fix those then the command will complete as expected.

**Comment by BeyondTheProof** [comment]
For those interested, there is also an issue where if the chromosome is not found in the bigwig file, it will raise the same error. Whether this is intentional or not, I don't know. I've worked around this by checking first if the chromosome is in `bigwig_reader.chroms()`

**Comment by dpryan79** [comment]
@BeyondTheProof That behavior is intentional. I want upstream packages to be able to know immediately if they're making nonsense queries.
