### ISSUE TITLE
plotProfile ValueError: left cannot be >= right deeptools 3.2.1

### ISSUE THREAD

**Issue by fansuogeng** [deeptools/deepTools#833]
I have one bed file and 6 bigwig files. I used computeMatrix and plotProfile to generate a plot. When --perGroup is not used, I got 6 plots. So I wanted them to pile together, so I activated --perGroup. That was when the problem arose. I'm using deeptools 3.2.1. Here is the error message:
Traceback (most recent call last):
  File "/home/micgen/bin/plotProfile", line 12, in <module>
    main(args)
  File "/lib/python2.7/site-packages/deeptools/plotProfile.py", line 959, in main
    prof.plot_heatmap()
  File "/lib/python2.7/site-packages/deeptools/plotProfile.py", line 566, in plot_heatmap
    plt.tight_layout()
  File "/lib/python2.7/site-packages/matplotlib/pyplot.py", line 1344, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/lib/python2.7/site-packages/matplotlib/figure.py", line 2031, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/lib/python2.7/site-packages/matplotlib/figure.py", line 1881, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/figure.py", line 237, in update
    raise ValueError('left cannot be >= right')
ValueError: left cannot be >= right

Just wondered if anyone has similar issues?

**Comment by dpryan79** [comment]
I tend to get that when the sample labels are really long, so try setting your own with `--samplesLabel` and see if that fixes things.

**Comment by fansuogeng** [comment]
Indeed! Thank you very much for the tip!
