### ISSUE TITLE
plotNumbers error in plotCorrelation

### ISSUE THREAD

**Issue by zentnerlab** [deeptools/deepTools#838]
Hi Devon,

I received the below-described error when attempting to plot the correlation values on top of the correlation heatmap in plotCorrelation.

deepTools version: 3.2.1
Python version: 2.7.15

plotCorrelation -in all_pca_matrix_confirmation.npz -c pearson --whatToPlot heatmap -o all_corrplot.pdf --removeOutliers --colorMap viridis --plotNumbers

Outliers were detected in the data. They will be removed to avoid bias in the pearson correlation.
Traceback (most recent call last):
  File "/N/u/gzentner/Karst/miniconda3/envs/chipseq-automation/bin/plotCorrelation", line 12, in <module>
    main(args)
  File "/N/u/gzentner/Karst/miniconda3/envs/chipseq-automation/lib/python2.7/site-packages/deeptools/plotCorrelation.py", line 253, in main
    plotHeight=args.plotHeight)
  File "/N/u/gzentner/Karst/miniconda3/envs/chipseq-automation/lib/python2.7/site-packages/deeptools/correlation.py", line 302, in plot_correlation
    cmap = cmap.from_list(colormap + "clipped",
AttributeError: 'ListedColormap' object has no attribute 'from_list'

Thanks for any help!

Gabe

**Comment by dpryan79** [comment]
What version of matplotlib do you have installed?

**Comment by zentnerlab** [comment]
2.2.3

**Comment by dpryan79** [comment]
This is now fixed in the develop branch and will work in the next release.
