### ISSUE TITLE
plotCorrelation scipy import error, undefined ztpqrt2_

### ISSUE THREAD

**Issue by JPascualAnaya** [deeptools/deepTools#840]
Hi there, 

I have problems to get plotCorrelation running. Although I've had no problems running other tools, I can't find a workaround for this.

I'm running the tools on a CentOS6.8.
deepTools, python and scipy versions are as follows:
```
$ deeptools --version
deeptools 3.2.1
```

```
$ python
Python 3.5.0 (default, Nov 18 2015, 16:13:49) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.2.1'
```

Any plotCorrelation command produces the same output. For instance:
```
$ plotCorrelation --version
Traceback (most recent call last):
  File "/home/champi/Software/deepTools_3.2.1/bin/plotCorrelation", line 5, in <module>
    from deeptools.plotCorrelation import main
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/deeptools/plotCorrelation.py", line 13, in <module>
    from deeptools.correlation import Correlation
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/deeptools/correlation.py", line 4, in <module>
    import scipy.cluster.hierarchy as sch
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/cluster/__init__.py", line 27, in <module>
    from . import vq, hierarchy
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/cluster/vq.py", line 75, in <module>
    from scipy.spatial.distance import cdist
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._spherical_voronoi import SphericalVoronoi
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/spatial/_spherical_voronoi.py", line 18, in <module>
    from scipy.spatial.distance import pdist
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/spatial/distance.py", line 125, in <module>
    from ..linalg import norm
  File "/home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/linalg/__init__.py", line 207, in <module>
    from ._decomp_update import *
  File "_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update
ImportError: /home/champi/Software/deepTools_3.2.1/lib/python3.5/site-packages/scipy/linalg/cython_lapack.cpython-35m-x86_64-linux-gnu.so: undefined symbol: ztpqrt2_

```

Any idea how to solve this? Any help is much appreaciated.

Cheers,
Juan

**Comment by dpryan79** [comment]
Try uninstalling and reinstalling scipy.
--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by JPascualAnaya** [comment]
That solved it, thanks!
