### ISSUE TITLE
I can not run any function

### ISSUE THREAD

**Issue by xiaocong3333** [deeptools/deepTools#856]
HI, I have install the newest version, 3.2.1, when I run any function of deeptools, such as:
./bamCoverage 
it will come with these issues, I do not know why. Had any one met this kind of issue?

Traceback (most recent call last):
  File "./bamCoverage", line 5, in <module>
    from deeptools.bamCoverage import main
  File "/home/congxiao/.local/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 8, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/home/congxiao/.local/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 9, in <module>
    from deeptools.utilities import getCommonChrNames
  File "/home/congxiao/.local/lib/python2.7/site-packages/deeptools/utilities.py", line 4, in <module>
    from deeptools.bamHandler import openBam
  File "/home/congxiao/.local/lib/python2.7/site-packages/deeptools/bamHandler.py", line 2, in <module>
    import pysam
  File "/home/congxiao/.local/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ImportError: libchtslib.so: cannot open shared object file: No such file or directory

**Comment by dpryan79** [comment]
You apparently need to reinstall pysam.

**Comment by xiaocong3333** [comment]
> You apparently need to reinstall pysam.
Thank you. It works!
