### ISSUE TITLE
testing local package installation

### ISSUE THREAD

**Issue by smoe** [deeptools/deepTools#858]
Hello,
I did not find instructions on what you preferred way to execute your unittests is. When I run tests from the root of the source tree as in
```
.../deeptools-3.3.0$ python3.7 -m unittest discover -v
test_writeBedGraph_cigar (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... ok
test_writeBedGraph_worker (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... ok
test_writeBedGraph_worker_ignore_duplicates (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... ok
test_writeBedGraph_worker_scaling (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... ok
test_writeBedGraph_worker_smoothing (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... ok
test_writeBedGraph_worker_zerotonan (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... ok
test_writeBedGraph_cigar (deeptools.test.test_writeBedGraph.TestWriteBedGraphCRAM) ... ok
test_writeBedGraph_worker (deeptools.test.test_writeBedGraph.TestWriteBedGraphCRAM) ... ok
test_writeBedGraph_worker_ignore_duplicates (deeptools.test.test_writeBedGraph.TestWriteBedGraphCRAM) ... ok
test_writeBedGraph_worker_scaling (deeptools.test.test_writeBedGraph.TestWriteBedGraphCRAM) ... ok
test_writeBedGraph_worker_smoothing (deeptools.test.test_writeBedGraph.TestWriteBedGraphCRAM) ... ok
test_writeBedGraph_worker_zerotonan (deeptools.test.test_writeBedGraph.TestWriteBedGraphCRAM) ... ok

----------------------------------------------------------------------
Ran 12 tests in 0.010s

OK
```
then everything looks so very nice. The default for the Debian packaging is to run this from within a "build" folder, i.e. only on those files that are to be installed and then it misses the files to test on. This then looks like this: 
```
   dh_auto_test -O--buildsystem=pybuild
        pybuild --test -i python{version} -p 3.7
I: pybuild base:217: cd /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build; python3.7 -m unittest discover -v
test_writeBedGraph_cigar (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... [E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
[E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
ERROR
test_writeBedGraph_worker (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... [E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
[E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
ERROR
test_writeBedGraph_worker_ignore_duplicates (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... [E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
[E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testB.bam
[E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testB.bam
ERROR
test_writeBedGraph_worker_scaling (deeptools.test.test_writeBedGraph.TestWriteBedGraph) ... [E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
[E::hts_open_format] Failed to open file /home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/.pybuild/cpython3_3.7_deeptools/build/deeptools/test/test_data/testA.bam
ERROR
.... many more ....
```
What worried me just a bit is that when taking other test suites from the root of the source tree, like nosetests3, I get errors. These look like funny with not finding itself:
```
...Traceback (most recent call last):
  File "/home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/deeptools/test/../../bin/plotPCA", line 4, in <module>
    from  deeptools import misc
ModuleNotFoundError: No module named 'deeptools'
E.................F......
```
which I initially accredited to the shebang line pointing to what is python2 in Debian, but I have patched that.  I also saw command lines that don't seem to fit:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/deeptools/test/test_computeMatrixOperations.py", line 102, in testrbind
    cmo.main(args)
  File "/home/moeller/git/med-team/deeptools/python-deeptools-3.3.0/deeptools/computeMatrixOperations.py", line 764, in main
    args = parse_arguments().parse_args(args)
  File "/usr/lib/python3.7/argparse.py", line 1758, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1996, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1936, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1864, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1047, in __call__
    parser.exit()
  File "/usr/lib/python3.7/argparse.py", line 2497, in exit
    _sys.exit(status)
SystemExit: 0
-------------------- >> begin captured stdout << ---------------------
usage: nosetests3 [-h] [--version]  ...

This tool performs a variety of operations on files produced by computeMatrix.

detailed help:

  computeMatrixOperations info -h

or

  computeMatrixOperations relabel -h

or

  computeMatrixOperations subset -h

or
....
```
I don't have the impression that everything would be completely off since of the many tests run, quite a few actually work:
```
Ran 108 tests in 9.340s

FAILED (errors=8, failures=1)
```
Can you help me with a pointer on how you want your tests to be run? Tell me if you consider these issues to be real and you want me to chase issues down on my end.

**Comment by dpryan79** [comment]
We use nosetests, such as for our CI testing: https://github.com/deeptools/deepTools/blob/master/.azure-pipelines/test-template.yml#L14

**Comment by smoe** [comment]
Many thanks. This helped to spot more of the "/usr/bin/env python" lines that I changed to "/usr/bin/python3".

There are two left. The first I solve by adding a PYTHONPATH that includes $(pwd):
```
/home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/test_readFiltering.py:79: ResourceWarning:

unclosed file <_io.BufferedReader name='/tmp/test_sieveFiltered.bam'>

ok
Test alignmentSieve with the --BED option ... ok
Test alignmentSieve --BED --shift ... ok
Checks everything that is in /bin/ ... plotPCA
Traceback (most recent call last):
  File "/home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/../../bin/plotPCA", line 4, in <module>
    from  deeptools import misc
ModuleNotFoundError: No module named 'deeptools'
ERROR

======================================================================
ERROR: Checks everything that is in /bin/
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/test_tools.py", line 17, in test_tools
    subprocess.check_call("{}/{} --version".format(ROOT, _file).split())
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/../../bin/plotPCA', '--version']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 84 tests in 3.864s
```
It stopped early because of a "-x" to nosetests3.  Tracing what invocates it, I can just reproduce it with
```
.../deeptools/test$ ../../bin/plotPCA --version
Traceback (most recent call last):
  File "../../bin/plotPCA", line 4, in <module>
    from  deeptools import misc
ModuleNotFoundError: No module named 'deeptools'
```
so the location of the module is not forwarded
```
.../deeptools/test$ PYTHONPATH=../.. ../../bin/plotPCA --version
plotPCA 3.3.0
```
This works fine enough to pass the autotest.

The second issue seems more serious as image sizes don't match:
```
======================================================================
FAIL: deeptools.test.testskip_heatmapper_images.test_plotHeatmap_multiple_colormap_no_boxes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/testskip_heatmapper_images.py", line 77, in test_plotHeatmap_multiple_colormap_no_boxes
    res = compare_images(ROOT + '/heatmap_master_multi_colormap_no_box.png', outfile.name, tolerance)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/compare.py", line 426, in compare_images
    rms = calculate_rms(expectedImage, actualImage)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/compare.py", line 356, in calculate_rms
    "actual size {}".format(expectedImage.shape, actualImage.shape))
matplotlib.testing.exceptions.ImageComparisonFailure: Image sizes do not match expected size: (2327, 1257, 3) actual size (2327, 1261, 3)
-------------------- >> begin captured logging << --------------------
matplotlib.colorbar: DEBUG: locator: <matplotlib.ticker.MaxNLocator object at 0x7f5d4c5f4050>
```
so this is 4 pixels higher. The version of matplotlib seems to be fine with your requirements, though:
```
ii  python3-matplotlib 3.0.2-2      amd64        Python based plotting system in a style similar to Matlab (Python 3)
$ grep matplot requirements.txt
matplotlib>=2.1.2
```
Is that test possibly overly sensitive? Or can it be made matplotlib-version dependent? This would hurt binary reproducibility, admittedly, but for that we have snapshot.debian.org/conda plus docker, right?

Many thanks!

Steffen

**Comment by dpryan79** [comment]
Regarding the image tests, those will fail unless you use exactly the matplotlib version as I do in the CI testing. Honestly, I would just skip most testing since that's all automated and we have thousands of installs across the globe that report any real problem.

Regarding changing the shebang, I don't know how the packaging process works in debian, but I would have assumed that files are installed into a given path and there's a script that then checks automatically for shebangs and other paths in text files that need to be changed. That's how we handle packaging in conda at least.

**Comment by smoe** [comment]
I'll see that I deactivate the heatmapper image test, then. The testing is not about confirming that your software is scientifically correct but about allowing some confidence that the Debian packaging does not mess it up. This helps backporting or to spot when some updated library has a silent API change that wrecks this package as a reverse dependency - there is only one version installed for each python module (or off each SONAME of a C library) at a  time, so things may easily fail. Also, the porting across architectures (ARM, MIPS, etc) at times finds issues via these autotests, often some subtle flaws in the C code, that are then addressed together with upstream. So, the Debian folks are very happy about them and introduce autotests to the packages where upstream does not have them.

With Debian, everything is installed into /, so we kind of expect know where to find other packages' libraries and executables at run time. This is actually not fully correct. It is installed into a newly created folder "debian/packagename" by the packager as a regular user. There is is tared up and the end user untares it as as root from /. That is why "chroot" environments are working so nicely. And of course we all look at conda and know why it is so successful - hey, I am using cnnda on our University cluster. The upstream source tree is meant not to be changed for Debian packaging at all. And if it is changed, then this becomes a patch in the folder "[debian/patches](https://salsa.debian.org/med-team/python-deeptools/blob/master/debian/patches/python2to3_for_executables.patch)" and a description of it in "debian/README.source" - well, I better create this now that I mention it. This is a bit annoying but is meant give upstream (you) some piece of mind about what we are doing with your development and users want to know, too, what is changed and why. Concerning the change of /usr/bin/env paths I agree that there should be a script that autocreates that patch. Maybe there is and I am just not aware of it.
