### ISSUE TITLE
Failing heatmapper unit tests

### ISSUE THREAD

**Issue by omsai** [deeptools/deepTools#863]
Here are the 5 failing tests:

```python-traceback
======================================================================                                                                                                                         
FAIL: deeptools.test.testskip_heatmapper_images.test_plotHeatmap_multiple_colors_muti_scales                                                                                                   
----------------------------------------------------------------------                                                                                                                         
Traceback (most recent call last):                                                                                                                                                             
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest                 
    self.test(*self.arg)                                                                                                                                                                       
  File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 67, in test_plotHeatmap_multiple_colors_muti_scales                       
    res = compare_images(ROOT + '/heatmap_master_multi_color.png', outfile.name, tolerance)                                                                                       
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-matplotlib-3.1.1-x7sjoxbgxn4ggueecq4cpbj5zq2fzwoo/lib/python3.7/site-packages/matplotlib/testing/compare.py", line 458, in c
ompare_images                                                                                                                                     
    rms = calculate_rms(expected_image, actual_image)                                                                                                                                          
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-matplotlib-3.1.1-x7sjoxbgxn4ggueecq4cpbj5zq2fzwoo/lib/python3.7/site-packages/matplotlib/testing/compare.py", line 366, in c
alculate_rms                                                                                                                                                                                   
    "actual size {}".format(expected_image.shape, actual_image.shape))                                                                                                                         
matplotlib.testing.exceptions.ImageComparisonFailure: Image sizes do not match expected size: (2327, 1257, 3) actual size (2327, 1253, 3)

======================================================================                                                                                                                         
FAIL: deeptools.test.testskip_heatmapper_images.test_plotHeatmap_multiple_colormap_no_boxes                                                                                                    
----------------------------------------------------------------------                                                                                                                         
Traceback (most recent call last):                                                                                                                                                             
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest                 
    self.test(*self.arg)                                                                                                                                                                       
  File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 77, in test_plotHeatmap_multiple_colormap_no_boxes
    res = compare_images(ROOT + '/heatmap_master_multi_colormap_no_box.png', outfile.name, tolerance)
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-matplotlib-3.1.1-x7sjoxbgxn4ggueecq4cpbj5zq2fzwoo/lib/python3.7/site-packages/matplotlib/testing/compare.py", line 458, in c
ompare_images
    rms = calculate_rms(expected_image, actual_image)
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-matplotlib-3.1.1-x7sjoxbgxn4ggueecq4cpbj5zq2fzwoo/lib/python3.7/site-packages/matplotlib/testing/compare.py", line 366, in c
alculate_rms
    "actual size {}".format(expected_image.shape, actual_image.shape))
matplotlib.testing.exceptions.ImageComparisonFailure: Image sizes do not match expected size: (2327, 1257, 3) actual size (2327, 1261, 3)

======================================================================
FAIL: deeptools.test.testskip_heatmapper_images.test_plotProfiler
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 98, in test_plotProfiler
    assert res is None, res
AssertionError: Error: Image files did not match.
  RMS Value: 45.091652940117896
  Expected:
    /tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/test_heatmapper//profile_master.png
  Actual:
    /tmp/plotHeatmap_test_wbd7fwrm.png
  Difference:
    /tmp/plotHeatmap_test_wbd7fwrm-failed-diff.png
  Tolerance:
    30

======================================================================                                                                  
FAIL: deeptools.test.testskip_heatmapper_images.test_plotProfiler_multibigwig                                                                 
----------------------------------------------------------------------                                                                                
Traceback (most recent call last):                                                                                                
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                                                                                                              
  File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 127, in test_plotProfiler_multibigwig
    assert res is None, res                                                                                                                    
AssertionError: Error: Image files did not match.                                                                                      
  RMS Value: 47.707079699945645                                                                                                       
  Expected:                                                                                                                                 
    /tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/test_heatmapper//profile_master_multi.png                   
  Actual:                                                                                                                             
    /tmp/plotHeatmap_test_z3xf5v_3.png                                                                                                        
  Difference:                                                                                                                           
    /tmp/plotHeatmap_test_z3xf5v_3-failed-diff.png                                                                                          
  Tolerance:                                                                                                                           
    30

======================================================================                                                                   
FAIL: deeptools.test.testskip_heatmapper_images.test_plotProfiler_multibigwig_pergroup                                                
----------------------------------------------------------------------                                                                  
Traceback (most recent call last):                                                                                                        
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                                                                                                              
  File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 137, in test_plotProfiler_multibigwig_pergroup
    assert res is None, res                                                                                                   
AssertionError: Error: Image files did not match.                                                                                        
  RMS Value: 47.52845368272629                                                                                                                 
  Expected:                                                                                                                             
    /tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/test_heatmapper//profile_master_multi_pergroup.png                
  Actual:                                                                                                                                             
    /tmp/plotHeatmap_test_ijq8rsip.png                                                                                            
  Difference:                                                                                                                                         
    /tmp/plotHeatmap_test_ijq8rsip-failed-diff.png                                                                                    
  Tolerance:                                                                                                                                  
    30 
```

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

```console
$ spack find -dvf py-deeptools ^python@3:
==> 1 installed package
-- linux-ubuntu18.04-x86_64 / gcc@7.4.0 -------------------------
    py-deeptools@3.3.0%gcc 
        ^py-deeptoolsintervals@0.1.9%gcc 
            ^python@3.7.4%gcc +bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib
                ^bzip2@1.0.8%gcc +shared
                ^expat@2.2.5%gcc +libbsd
                    ^libbsd@0.9.1%gcc 
                ^gdbm@1.18.1%gcc 
                    ^readline@7.0%gcc 
                        ^ncurses@6.1%gcc ~symlinks~termlib
                ^gettext@0.19.8.1%gcc +bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz
                    ^libxml2@2.9.9%gcc ~python
                        ^libiconv@1.15%gcc 
                        ^xz@5.2.4%gcc 
                        ^zlib@1.2.11%gcc +optimize+pic+shared
                    ^tar@1.31%gcc 
                ^libffi@3.2.1%gcc 
                ^openssl@1.1.1c%gcc +systemcerts
                ^sqlite@3.28.0%gcc +fts~functions
        ^py-matplotlib@3.1.1%gcc ~animation backend=agg +image~latex~movies
            ^freetype@2.9.1%gcc  patches=08466355e8649235ff01f13b3e56bbd551c7cfb2ca97903cc11575c163ea32a3
                ^libpng@1.6.34%gcc 
            ^py-cycler@0.10.0%gcc 
                ^py-six@1.8.0%gcc 
            ^py-kiwisolver@1.0.1%gcc 
            ^py-numpy@1.17.0%gcc +blas+lapack
                ^openblas@0.3.7%gcc +avx2~avx512 cpu_target=auto ~ilp64+pic+shared threads=none ~virtual_machine
            ^py-pillow@5.4.1%gcc ~freetype+jpeg~jpeg2000~lcms~tiff+zlib
                ^libjpeg-turbo@2.0.2%gcc 
            ^py-pyparsing@2.3.1%gcc 
            ^py-python-dateutil@2.8.0%gcc 
            ^py-setuptools@41.0.1%gcc 
        ^py-numpydoc@0.6.0%gcc 
        ^py-plotly@2.2.0%gcc 
            ^py-pytz@2014.9%gcc 
            ^py-requests@2.3.0%gcc 
        ^py-py2bit@0.2.1%gcc 
        ^py-pybigwig@0.3.4%gcc 
            ^curl@7.63.0%gcc ~darwinssl~gssapi~libssh~libssh2~nghttp2
        ^py-pysam@0.14.1%gcc 
            ^bcftools@1.9%gcc 
                ^htslib@1.9%gcc 
                ^libzip@1.2.0%gcc 
            ^samtools@1.9%gcc 
        ^py-scipy@1.3.0%gcc
```

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

```console
$ spack install --verbose --test root py-deeptools ^python@3:
```

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

```python-traceback
$ spack install --verbose --test root py-deeptools ^python@3:
...
Ran 108 tests in 33.559s                                                                                                                   
                      
FAILED (failures=5)                                
Test failed: <unittest.runner.TextTestResult run=108 errors=0 failures=5>
error: Test failed: <unittest.runner.TextTestResult run=108 errors=0 failures=5>
==> Error: ProcessError: Command exited with status 1:
    '/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/python-3.7.4-kt3cckhkwmdtuuz7ig2qlg6a33klntqa/bin/python3.7' '-s' 'setup.py' '--no-user-cfg' 'test'
         
4 errors found in build log:                                                       
     1496    ----------------------------------------------------------------------
     1497    Traceback (most recent call last):
     1498      File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
     1499        self.test(*self.arg)                                                 
     1500      File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 98, in test_plotProfiler
     1501        assert res is None, res
  >> 1502    AssertionError: Error: Image files did not match.
     1503      RMS Value: 45.091652940117896                                                        
     1504      Expected:
     1505        /tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/test_heatmapper//profile_master.png
     1506      Actual:                                                                     
     1507        /tmp/plotHeatmap_test_wbd7fwrm.png                                                                         
     1508      Difference:                                                      

     ...

     1973    ----------------------------------------------------------------------
     1974    Traceback (most recent call last):
     1975      File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
     1976        self.test(*self.arg)
     1977      File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 127, in test_plotProfiler_multibigwig
     1978        assert res is None, res
  >> 1979    AssertionError: Error: Image files did not match.
     1980      RMS Value: 47.707079699945645
     1981      Expected:
     1982        /tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/test_heatmapper//profile_master_multi.png
     1983      Actual:
     1984        /tmp/plotHeatmap_test_z3xf5v_3.png
     1985      Difference:

     ...

     1992    ----------------------------------------------------------------------
     1993    Traceback (most recent call last):
     1994      File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-nose-1.3.7-a2h5socbxpgbybszf34iyox7gzpqzkn5/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
     1995        self.test(*self.arg)
     1996      File "/tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/testskip_heatmapper_images.py", line 137, in test_plotProfiler_multibigwig_pergroup
     1997        assert res is None, res
  >> 1998    AssertionError: Error: Image files did not match.
     1999      RMS Value: 47.52845368272629
     2000      Expected:
     2001        /tmp/pan14001/spack-stage/spack-stage-6oujw919/spack-src/deeptools/test/test_heatmapper//profile_master_multi_pergroup.png
     2002      Actual:
     2003        /tmp/plotHeatmap_test_ijq8rsip.png
     2004      Difference:

     ...

     2008
     2009    ----------------------------------------------------------------------
     2010    Ran 108 tests in 33.559s
     2011
     2012    FAILED (failures=5)
     2013    Test failed: <unittest.runner.TextTestResult run=108 errors=0 failures=5>
  >> 2014    error: Test failed: <unittest.runner.TextTestResult run=108 errors=0 failures=5>

See build log for details:
  /opt/spack/var/spack/stage/py-deeptools-3.3.0-52rsxagbuwcaifuvyrobjsiio2bidy2z/spack-build-out.txt
```

See the full [spack-build-out.txt](https://github.com/deeptools/deepTools/files/3512184/spack-build-out.txt) log attached.

**Comment by dpryan79** [comment]
You need a particular version of matplotlib installed for those tests to work. Just ignore them.
