### ISSUE TITLE
ValueError: could not convert string to float (parsing deepBlue data.)

### ISSUE THREAD

**Issue by yyoshiaki** [deeptools/deepTools#870]
Hi, I encountered an error below when I played with deepBlue data. 

versions
deeptools 3.3.0
Python 3.7.3

commands
```
wget https://sourceforge.net/projects/rseqc/files/BED/Mouse_Mus_musculus/mm9_RefSeq.bed.gz/download -O mm9_RefSeq.bed.gz
computeMatrix scale-regions -S ENCFF001OVY -R mm9_RefSeq.bed.gz -b 1000 -p 40 -out Treg.DNase.mm9.ENCODE.matrix.gz
```

```
Preloading the following deepBlue files: ENCFF001OVY
Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/yyasumizu/anaconda3/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 412, in main
    res = list(map(db.preloadWrapper, deepBlueFiles))
  File "/home/yyasumizu/anaconda3/lib/python3.7/site-packages/deeptools/deepBlue.py", line 115, in preloadWrapper
    return res.preload(regs, tmpDir=args.deepBlueTempDir)
  File "/home/yyasumizu/anaconda3/lib/python3.7/site-packages/deeptools/deepBlue.py", line 281, in preload
    bw.addEntries([k], [int(interval[0]) - 1], ends=[int(interval[1]) - 1], values=[float(interval[2])])
ValueError: could not convert string to float: 
```

Best,
Yoshiaki

**Comment by dpryan79** [comment]
Try decreasing the number of threads. For remote files you can quickly overwhelm the remote server with connections, so no more than 5 threads is recommended.

**Comment by yyoshiaki** [comment]
Thank you for your quick reply! The error was not solved.

```
 $ computeMatrix scale-regions -S ENCFF001OVY -R mm9_RefSeq.bed.gz -b 1000 -p 5 -out Treg.DNase.mm9.ENCODE.matrix.gz                                                                                                                          
Preloading the following deepBlue files: ENCFF001OVY
Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/yyasumizu/anaconda3/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 412, in main
    res = list(map(db.preloadWrapper, deepBlueFiles))
  File "/home/yyasumizu/anaconda3/lib/python3.7/site-packages/deeptools/deepBlue.py", line 115, in preloadWrapper
    return res.preload(regs, tmpDir=args.deepBlueTempDir)
  File "/home/yyasumizu/anaconda3/lib/python3.7/site-packages/deeptools/deepBlue.py", line 281, in preload
    bw.addEntries([k], [int(interval[0]) - 1], ends=[int(interval[1]) - 1], values=[float(interval[2])])
ValueError: could not convert string to float: 
```

**Comment by yyoshiaki** [comment]
ENCFF001OVY was a peak file and not a signal file. I'm so sorry for being careless.
