### ISSUE TITLE
Cannot run bamcoverage

### ISSUE THREAD

**Issue by huangxingnan1994** [deeptools/deepTools#877]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi there, 
I am using bamCoverage to generate bw files. But it report an error as follows:

```
 bamCoverage
Traceback (most recent call last):
  File "/public/home/xnhuang_gibh/anaconda3/bin/bamCoverage", line 5, in <module>
    from deeptools.bamCoverage import main
  File "/public/home/xnhuang_gibh/anaconda3/lib/python3.7/site-packages/deeptools/bamCoverage.py", line 8, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/public/home/xnhuang_gibh/anaconda3/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 9, in <module>
    from deeptools.utilities import getCommonChrNames
  File "/public/home/xnhuang_gibh/anaconda3/lib/python3.7/site-packages/deeptools/utilities.py", line 4, in <module>
    from deeptools.bamHandler import openBam
  File "/public/home/xnhuang_gibh/anaconda3/lib/python3.7/site-packages/deeptools/bamHandler.py", line 2, in <module>
    import pysam
  File "/public/software/genomics/unstable/CPAT-1.2.1/public/sugon/software/Python-2.7/lib/python2.7/site-packages/pysam/__init__.py", line 1, in <module>
    from csamtools import *
ImportError: /public/software/genomics/unstable/CPAT-1.2.1/public/sugon/software/Python-2.7/lib/python2.7/site-packages/csamtools.so: undefined symbol: _Py_ZeroStruct
```

I installed deeptools via conda. 
deeptools version 3.3.1
python version 3.7.3

I ran command `ops='-bs 20 --smoothLength 60 -p=20 --normalizeUsingRPKM -e 300 --ignoreDuplicates'
bamCoverage --bam $inp -o ./${out}.bw $ops
` and `bamCoverage`.

**Comment by dpryan79** [comment]
Try updating pysam, apparently there's something wrong with it.

**Comment by huangxingnan1994** [comment]
Thanks
