### ISSUE TITLE
alignmentSieve (3.3.1) no space left on device

### ISSUE THREAD

**Issue by geejaytee** [deeptools/deepTools#890]
I'm using alignmentSieve (3.3.1) to fragment my BAM files into differently-sized DNA fragments, but for some subsets with a large number of reads, I get a "No space left on device" error which appears to be because the file is too large to write to temporary storage (I have multiple alignmentSieve processes running simultaneously on a SGE batch job).

Where can I find the config option to move the temporary file storage to a different location where there is plenty of storage?

I'm running v3.3.1, installed using anaconda on a SGE grid engine with each node running CentOS 7.7.1908.

**Comment by geejaytee** [comment]
Specifically, the error is:

    [E::bgzf_flush] File write failed (wrong size)
    Traceback (most recent call last):
      File "<home>/anaconda/deepTools/bin/alignmentSieve", line 12, in <module>
        main(args)
      File "<home>/anaconda/deepTools/lib/python3.7/site-packages/deeptools/alignmentSieve.py", line 390, in main
        verbose=args.verbose)
      File "<home>/anaconda/deepTools/lib/python3.7/site-packages/deeptools/mapReduce.py", line 146, in mapReduce
        res = list(map(func, TASKS))
      File "<home>/anaconda/deepTools/lib/python3.7/site-packages/deeptools/alignmentSieve.py", line 331, in filterWorker
        ofh.write(read)
      File "pysam/libcalignmentfile.pyx", line 1704, in pysam.libcalignmentfile.AlignmentFile.write
      File "pysam/libcalignmentfile.pyx", line 1738, in pysam.libcalignmentfile.AlignmentFile.write
    OSError: sam_write1 failed with error code -1
    [E::bgzf_close] File write failed
    OSError: [Errno 28] No space left on device
    Exception ignored in: 'pysam.libcalignmentfile.AlignmentFile.__dealloc__'
    OSError: [Errno 28] No space left on device

and the command line is:

    alignmentSieve -b $infile -o $outfile2 --minFragmentLength 150 --maxFragmentLength 250

[$infile and $outfile2 are variables for the infile and outfile]

**Comment by dpryan79** [comment]
Please set $TMPDIR to somewhere with space.
