### ISSUE TITLE
3.3.1 test_readFiltering.py fails

### ISSUE THREAD

**Issue by smoe** [deeptools/deepTools#903]
Hello,
This one I have not observed with 3.3.0. When testing, a file seems to be used before that was closed. I looked around but the only idea I had was
```
--- a/deeptools/alignmentSieve.py
+++ b/deeptools/alignmentSieve.py
@@ -380,6 +380,7 @@ def main(args=None):
     total = mapped + unmapped
     chrom_sizes = [(x, y) for x, y in zip(bam.references, bam.lengths)]
     chromDict = {x: y for x, y in zip(bam.references, bam.lengths)}
+    bam.close()
 
     # Filter, writing the results to a bunch of temporary files
     res = mapReduce([args, chromDict],

```
Which makes no difference.

Here the report.
```
Minimal testing ... ok
--minMappingQuality 10 --samFlagExclude 512 --ignoreDuplicates -bl ... ok
Test filtering a BAM file by MAPQ, flag, and blacklist ... /home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/test_readFiltering.py:75: ResourceWarning:

unclosed file <_io.BufferedReader name='/tmp/test_sieve.bam'>

FAIL

======================================================================
FAIL: Test filtering a BAM file by MAPQ, flag, and blacklist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moeller/git/med-team/deeptools/python-deeptools/deeptools/test/test_readFiltering.py", line 76, in test_sieve
    assert(h == "977bdab227a4dbfa3fc9f27c23a3e0b7")
AssertionError

----------------------------------------------------------------------
Ran 81 tests in 3.807s

FAILED (failures=1)
```

**Comment by dpryan79** [comment]
I'm not sure why you're observing that, the same test passed CI testing. Perhaps an increase in pysam version has slightly changed the output, which produces a different sha then.

**Comment by smoe** [comment]
Pysam is 0.15.3.

**Comment by dpryan79** [comment]
Hmm, I can't reproduce this with python 3.6 or 3.7 and pysam 0.15.3, at least when installing things via conda. My guess is that this was some sort of transient error that resulted in a truncated file. Run the test again and let me know if it's still failing.
