### ISSUE TITLE
bam Compare no space left on divice issue

### ISSUE THREAD

**Issue by Yue2308** [deeptools/deepTools#927]
command:
bamCompare --scaleFactorsMethod SES --operation subtract --binSize 5 -b1 bam_mm10/TKO_0h_H3K27ac_WT_ChIP_seq.sorted.nodup.merged.bam -b2 bam_mm10/TKO_Input_H3K27ac.sorted.nodup.merged.bam -o bamCompare/TKO_0h_H3K27ac_WT_ChIP_seq.sorted.nodup.merged.input_normalized.bw -of bigwig

Error message:
Traceback (most recent call last):
  File "/home/yl2308/apps/anaconda3/envs/deeptools-3.3.2/bin/bamCompare", line 12, in <module>
    main(args)
  File "/home/yl2308/apps/anaconda3/envs/deeptools-3.3.2/lib/python3.7/site-packages/deeptools/bamCompare.py", line 309, in main
    wr.run(FUNC, func_args, args.outFileName, blackListFileName=args.blackListFileName, format=args.outFileFormat, smoothLength=args.smoothLength)
  File "/home/yl2308/apps/anaconda3/envs/deeptools-3.3.2/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 152, in run
    numberOfProcessors=self.numberOfProcessors)
  File "/home/yl2308/apps/anaconda3/envs/deeptools-3.3.2/lib/python3.7/site-packages/deeptools/mapReduce.py", line 146, in mapReduce
    res = list(map(func, TASKS))
  File "/home/yl2308/apps/anaconda3/envs/deeptools-3.3.2/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 27, in writeBedGraph_wrapper
    return WriteBedGraph.writeBedGraph_worker(*args)
  File "/home/yl2308/apps/anaconda3/envs/deeptools-3.3.2/lib/python3.7/site-packages/deeptools/writeBedGraph.py", line 271, in writeBedGraph_worker
    line_string.format(chrom, writeStart, writeEnd, previous_value))
OSError: [Errno 28] No space left on device

Hi, I met the same problem as issue #87 when I tried to run bamCompare, but the link you sent couldn't be opened anymore. If there a way to fix this problem right now?

Thanks

**Comment by dpryan79** [comment]
DeepTools will respect the TMPDIR environment variable. Just point that to a convenient place for temp files.

**Comment by re2srm** [comment]
Hello, I am getting the same issue. 

I have tried setting the TMPDIR variable to a location with free space but I still get the same error. In issue #87 it was recemmended to edit deeptools.cfg but I cant find this file (may be because I have installed deeptools using conda?). 

Would appreciate any ideas.

**Comment by dpryan79** [comment]
That config file hasn't existed in a number of years, ignore #87. Try setting `TMP` and `TEMP` as well. Otherwise maybe the full error message will prove helpful.

**Comment by re2srm** [comment]
Tried setting TMP and TEMP as well but still got the same error. Here is the full error:

Traceback (most recent call last):
  File "/scratch/ucsc_conda/deeptools/bin/bigwigCompare", line 12, in <module>
    main(args)
  File "/scratch/ucsc_conda/deeptools/lib/python2.7/site-packages/deeptools/bigwigCompare.py", line 172, in main
    extendPairedEnds=False)
  File "/scratch/ucsc_conda/deeptools/lib/python2.7/site-packages/deeptools/writeBedGraph_bam_and_bw.py", line 220, in writeBedGraph
    verbose=verbose)
  File "/scratch/ucsc_conda/deeptools/lib/python2.7/site-packages/deeptools/mapReduce.py", line 146, in mapReduce
    res = list(map(func, TASKS))
  File "/scratch/ucsc_conda/deeptools/lib/python2.7/site-packages/deeptools/writeBedGraph_bam_and_bw.py", line 42, in writeBedGraph_wrapper
    return writeBedGraph_worker(*args)
  File "/scratch/ucsc_conda/deeptools/lib/python2.7/site-packages/deeptools/writeBedGraph_bam_and_bw.py", line 133, in writeBedGraph_worker
    writeEnd, previousValue)))
IOError: [Errno 28] No space left on device

**Comment by dpryan79** [comment]
OK, I think I see the issue. If there's a shared memory partition then that will be used instead, since (A) that's fast and (B) on clusters it's usually large enough for something smallish. Can you run the following?

    df -h /dev/shm

My guess is that the free space is quite small (say <1GB). The solution would be to free up some space there.

**Comment by re2srm** [comment]
Thanks, I ran the command and it says there is only 256mb available:

Filesystem      Size  Used Avail Use% Mounted on
tmpfs           256M   12K  256M   1% /dev/shm

Is there anything I can do about this? The space allocated to me on the cluster is a few terabytes and most of it is free.

**Comment by dpryan79** [comment]
I need to change how this is handled internally, since it shouldn't be forcing /dev/shm when the environment variables are set. I'll push out a new release that fixes that now.

**Comment by dpryan79** [comment]
3.4.1 (due shortly) will fix this behavior, so TMPDIR will be properly respected.

**Comment by re2srm** [comment]
Great. Thanks a lot!
