### ISSUE TITLE
computeGCBias - matplotlib axis limits error

### ISSUE THREAD

**Issue by giusem** [deeptools/deepTools#969]
deeptools 3.4.3
python 3.7.6
matplotlib-base 3.2.2.

command:
computeGCBias -b ~/CLD_demo_project/CNV_visualization_test/03-mapping/cho_horizon_test_merged.bam -g ~/repository/cho_horizon_test/2bit/CHO_Horizon_test.2bit --effectiveGenomeSize 450000 -o cho_horizon_test_merged_gc_freq.tsv --biasPlot cho_horizon_test_merged_gc_freq.png

output:
filter_out: None
extra_sampling_file: None
genome_size: 456350
total_reads: 30552
reads_per_bp: 0.06789333333333333
max_reads: 99.0
min_reads: 0.0
computing frequencies
stepSize: 1
Traceback (most recent call last):
  File "/u/gsemplic/miniconda3/envs/deeptools/bin/computeGCBias", line 12, in <module>
    main(args)
  File "/u/gsemplic/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/computeGCBias.py", line 726, in main
    plotGCbias(args.biasPlot, data, reads_per_gc, args.regionSize, image_format=args.plotFileFormat)
  File "/u/gsemplic/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/computeGCBias.py", line 608, in plotGCbias
    ax1.set_ylim(0 - (y_max * 0.05), y_max * 1.05)
  File "/u/gsemplic/miniconda3/envs/deeptools/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3577, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "/u/gsemplic/miniconda3/envs/deeptools/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3101, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
(deeptools)

**Comment by LeilyR** [comment]
It is difficult for me to say what exactly caused that error message since I cannot reproduce it. But as the message says, it happens because y_max was either NaN or Inf, These values come from the whisker, so I wonder if you had some strange outlier that whisker returned Nan/Inf. Maybe you can check the output text file, if it has been generated. Other than that, I can add a parameter where you can specify the quantiles  of your interest and see if that solve your problem.

**Comment by giusem** [comment]
Hi Leily

Nice to hear from you again. I talked to Devon about it as well (since we are working together it was the fastest way) and he mentioned that he found the error. He nevertheless asked me write the issue down Probably best you talk to him if you want to know the root. 

Best,
Giuseppe

**Comment by LeilyR** [comment]
Hi Giuseppe,
Nice to hear from you too ! I have already noticed that he had PR for that. Thanks for heads up! I am not going to touch the code. :)
Cheers,
Leily
