### ISSUE TITLE
plotEnrichment - multiple processors

### ISSUE THREAD

**Issue by nuin** [deeptools/deepTools#988]
Hi 

I am getting this error when running with the `-p` or `--numberOfProcessors` option.

```
plotEnrichment -b BAM/my_bam.bam --BED /opt/BED/Cancer_panel.bed --outRawCounts test --numberOfProcessors 16
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/nuin/Envs/pipeline/lib/python3.8/site-packages/deeptools/plotEnrichment.py", line 302, in getEnrichment_worker
    for x in gtf.features:
NameError: name 'gtf' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nuin/Envs/pipeline/bin/plotEnrichment", line 12, in <module>
    main(args)
  File "/Users/nuin/Envs/pipeline/lib/python3.8/site-packages/deeptools/plotEnrichment.py", line 549, in main
    res = mapReduce([args, defaultFragmentLength],
  File "/Users/nuin/Envs/pipeline/lib/python3.8/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
NameError: name 'gtf' is not defined
```

freshly installed depptools with Python 3.8.5 (installed via pip).

Thanks a lot

**Comment by LeilyR** [comment]
It does not look like a multi processing error. Did it work with `-p 1` you mean?! It complains about not finding gtf. Could you please take care of all dependencies? The best would be installing the tool via conda. Also I am afraid it does not have a support for 3.8 yet. would you mind trying it with python 3.6 or 3.7? Let us know if the issue was still there.

**Comment by LeilyR** [comment]
I hope that your issue has been solved by installing the dependencies. so, for now I close this issue but feel free to reopen it, if there is still any problem left.
