### ISSUE TITLE
computeMatrixOperations cbind  - different input array dimensions

### ISSUE THREAD

**Issue by martindemko** [deeptools/deepTools#989]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

deeptools 3.4.3
Python 3.7.1

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

```
computeMatrixOperations cbind -m stage240_Smida_ChiP-Seq_pilot.WT/ChIP-seq_profile_investigation/peaks_profile/over_all_genes/WT_TFEB/pooled/coverage_matrix.no_dups.mtx.gz stage240_Smida_ChiP-Seq_pilot.WT/ChIP-seq_profile_investigation/peaks_profile/over_all_genes/WT_TFEB/rep2/coverage_matrix.no_dups.mtx.gz stage240_Smida_ChiP-Seq_pilot.WT/ChIP-seq_profile_investigation/peaks_profile/over_all_genes/WT_TFEB/rep1/coverage_matrix.no_dups.mtx.gz -o stage240_Smida_ChiP-Seq_pilot.WT/ChIP-seq_profile_investigation/peaks_profile/over_all_genes/WT_TFEB/all/coverage_matrix.no_dups.mtx.tmp.gz
```

```
Traceback (most recent call last):
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/e08f929a/bin/computeMatrixOperations", line 12, in <module>
    main(args)
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/e08f929a/lib/python3.7/site-packages/deeptools/computeMatrixOperations.py", line 812, in main
    cbindMatrices(hm, args)
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/e08f929a/lib/python3.7/site-packages/deeptools/computeMatrixOperations.py", line 521, in cbindMatrices
    hm.matrix.matrix = np.hstack((hm.matrix.matrix, np.empty(hm2.matrix.matrix.shape)))
  File "<__array_function__ internals>", line 6, in hstack
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/e08f929a/lib/python3.7/site-packages/numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 200304 and the array at index 1 has size 200302
```

There is an information in help  which contradicts this behaviour:

```
cbind       merge multiple matrices by concatenating them left to right.                                                                                                                                                           
                No assumptions are made about the row order. Regions not                                                                                                                                                               
                present in the first file specified are ignored. Regions                                                                                                                                                               
                missing in subsequent files will result in NAs. Regions are                                                                                                                                                            
                matches based on the first 6 columns of the computeMatrix                                                                                                                                                              
                output (essentially the columns in a BED file).
```

**Comment by LeilyR** [comment]
This is not what it says. They did not mean to say that the regions can have different length, but in case you have two set of regions with the same length and the regions are not the same, like this:
from the first matrix:        from the second matrix:  
chr2 100000 2000000     chr1 2000000 3000000
then in this case on the final matrix you will have:
chr2 100000 2000000         values_of_first_matrix       NaN 
and  chr1 2000000 3000000 is getting ignored. 
Though, I agree that the help message may not be so clear and might need a bit of an improvement.

**Comment by martindemko** [comment]
Ok, thank you for clarification. At least now I understand what does it mean.
